from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol


class AcquisitionStore(Protocol):
    def create_source(self, value: dict[str, object]) -> dict[str, object]: ...
    def get_source(self, source_id: str) -> dict[str, object] | None: ...
    def list_sources(self, source_type: str | None = None, status: str | None = None) -> list[dict[str, object]]: ...
    def update_source(self, source_id: str, value: dict[str, object]) -> dict[str, object] | None: ...
    def delete_source(self, source_id: str) -> dict[str, object] | None: ...

    def create_crawl_job(self, value: dict[str, object]) -> dict[str, object]: ...
    def get_crawl_job(self, job_id: str) -> dict[str, object] | None: ...
    def list_crawl_jobs(self, source_id: str | None = None, status: str | None = None) -> list[dict[str, object]]: ...
    def claim_crawl_job(
        self, worker_id: str, *, now: datetime, lease: timedelta
    ) -> dict[str, object] | None: ...
    def recover_expired_crawl_jobs(self, *, now: datetime) -> int: ...
    def mark_job_running(self, job_id: str) -> bool: ...
    def mark_job_failed(self, job_id: str, error: str, *, retryable: bool = True) -> bool: ...
    def retry_crawl_job(self, job_id: str) -> dict[str, object]: ...
    def cancel_crawl_job(self, job_id: str) -> dict[str, object]: ...

    def save_snapshot(self, job_id: str, source_id: str, external_id: str, raw_content: dict[str, object], source_version: str, content_type: str, metadata: dict[str, object] | None) -> dict[str, object]: ...
    def complete_crawl_job(self, job_id: str, source_id: str, records: list[dict[str, object]]) -> dict[str, object]: ...
    def list_snapshots(self, source_id: str, offset: int = 0, limit: int = 50) -> list[dict[str, object]]: ...
    def list_snapshot_observations(self, job_id: str) -> list[dict[str, object]]: ...

    def create_bundle_for_job(self, job_id: str, source_id: str, snapshot_ids: list[str], bundle_type: str) -> dict[str, object]: ...
    def get_bundle(self, bundle_id: str) -> dict[str, object] | None: ...
    def get_bundle_for_job(self, job_id: str) -> dict[str, object] | None: ...

    def enqueue_outbox(self, aggregate_type: str, aggregate_id: str, event_type: str, payload: dict[str, object]) -> dict[str, object]: ...
    def poll_outbox(self, status: str = "pending", limit: int = 20) -> list[dict[str, object]]: ...
    def claim_outbox(self, worker_id: str, *, now: datetime, lease: timedelta, limit: int = 20) -> list[dict[str, object]]: ...
    def recover_expired_outbox(self, *, now: datetime) -> int: ...
    def mark_outbox_processed(self, outbox_id: str, worker_id: str) -> bool: ...
    def mark_outbox_failed(self, outbox_id: str, worker_id: str, error: str) -> bool: ...
