"""frozen initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-13 18:33:51.382253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_index_if_exists(name: str, table_name: str) -> None:
    indexes = {
        item["name"]
        for item in sa.inspect(op.get_bind()).get_indexes(table_name)
    }
    if name in indexes:
        op.drop_index(name, table_name=table_name)


def _drop_table_if_exists(name: str) -> None:
    if sa.inspect(op.get_bind()).has_table(name):
        op.drop_table(name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_configs',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('duplicate_clusters',
    sa.Column('cluster_key', sa.String(length=80), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_documents',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_credibility', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_documents_document_id'), 'jd_documents', ['document_id'], unique=True)
    op.create_table('position_categories',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skill_categories',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('category_code', sa.String(length=80), nullable=False),
    sa.Column('subcategory_code', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id')
    )
    op.create_table('standard_positions',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_candidate_requirements',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_company_facts',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_employment_facts',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_task_requirements',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_evidence',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_ref', sa.String(length=80), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.String(length=30), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_evidence_document_id'), 'extraction_evidence', ['document_id'], unique=False)
    op.create_table('graph_build_runs',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_extraction_records',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_extraction_records_document_id'), 'jd_extraction_records', ['document_id'], unique=False)
    op.create_table('jd_normalized_records',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('map_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_normalized_records_document_id'), 'jd_normalized_records', ['document_id'], unique=False)
    op.create_table('jd_quality_assessments',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('duplicate_score', sa.Float(), nullable=False),
    sa.Column('copy_risk_score', sa.Float(), nullable=False),
    sa.Column('inflation_score', sa.Float(), nullable=False),
    sa.Column('effective_sample_weight', sa.Float(), nullable=False),
    sa.Column('assessed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('skill_aliases',
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('unresolved_normalization_items',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_build_samples',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reasons', sa.JSON(), nullable=False),
    sa.Column('effective_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_versions',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('normalization_map_version', sa.String(length=50), nullable=False),
    sa.Column('rollback_from_version_id', sa.Integer(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.ForeignKeyConstraint(['rollback_from_version_id'], ['graph_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_job_classifications',
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=True),
    sa.Column('source_title', sa.String(length=200), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['jd_normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_requirement_records',
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['jd_normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_requirement_aggregate_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_skill_relation_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('auto_weight', sa.Float(), nullable=False),
    sa.Column('manual_weight', sa.Float(), nullable=True),
    sa.Column('final_weight', sa.Float(), nullable=False),
    sa.Column('auto_confidence', sa.Float(), nullable=False),
    sa.Column('manual_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('auto_importance_level', sa.String(length=20), nullable=False),
    sa.Column('manual_importance_level', sa.String(length=20), nullable=True),
    sa.Column('final_importance_level', sa.String(length=20), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_run_id', 'skill_id')
    )
    op.create_table('position_task_aggregate_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_skill_records',
    sa.Column('normalized_requirement_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=True),
    sa.Column('canonical_name', sa.String(length=200), nullable=True),
    sa.Column('category_code', sa.String(length=80), nullable=True),
    sa.Column('subcategory_code', sa.String(length=80), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_requirement_id'], ['normalized_requirement_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_task_events',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_skill_supports',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('normalized_skill_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_table_if_exists('position_skill_supports')
    _drop_table_if_exists('review_task_events')
    _drop_table_if_exists('normalized_skill_records')
    _drop_table_if_exists('review_tasks')
    _drop_table_if_exists('position_task_aggregate_drafts')
    _drop_table_if_exists('position_skill_relation_drafts')
    _drop_table_if_exists('position_requirement_aggregate_drafts')
    _drop_table_if_exists('normalized_requirement_records')
    _drop_table_if_exists('normalized_job_classifications')
    _drop_table_if_exists('graph_versions')
    _drop_table_if_exists('graph_build_samples')
    _drop_table_if_exists('unresolved_normalization_items')
    _drop_table_if_exists('skill_aliases')
    _drop_table_if_exists('jd_quality_assessments')
    _drop_index_if_exists('ix_jd_normalized_records_document_id', 'jd_normalized_records')
    _drop_table_if_exists('jd_normalized_records')
    _drop_index_if_exists('ix_jd_extraction_records_document_id', 'jd_extraction_records')
    _drop_table_if_exists('jd_extraction_records')
    _drop_table_if_exists('graph_build_runs')
    _drop_index_if_exists('ix_extraction_evidence_document_id', 'extraction_evidence')
    _drop_table_if_exists('extraction_evidence')
    _drop_table_if_exists('extracted_task_requirements')
    _drop_table_if_exists('extracted_employment_facts')
    _drop_table_if_exists('extracted_company_facts')
    _drop_table_if_exists('extracted_candidate_requirements')
    _drop_table_if_exists('audit_logs')
    _drop_table_if_exists('users')
    _drop_table_if_exists('standard_positions')
    _drop_table_if_exists('skills')
    _drop_table_if_exists('skill_categories')
    _drop_table_if_exists('position_categories')
    _drop_index_if_exists('ix_jd_documents_document_id', 'jd_documents')
    _drop_table_if_exists('jd_documents')
    _drop_table_if_exists('duplicate_clusters')
    _drop_table_if_exists('algorithm_configs')
    # ### end Alembic commands ###
