from app.application.use_cases import (
    AnalyzeDependenciesUseCase,
    AutoReviewBuildUseCase,
    BuildGraphUseCase,
    BuildJobUseCase,
    BatchReviewTasksUseCase,
    DependencyReferenceUseCase,
    AssessJDQualityUseCase,
    ClaimReviewTaskUseCase,
    CompleteReviewTaskUseCase,
    ConfirmExtractionUseCase,
    CompareBuildWatermarksUseCase,
    CreateMappingCandidateUseCase,
    CreateReviewTaskUseCase,
    ExtractJDUseCase,
    ImportExtractionResultUseCase,
    ImportNormalizedResultUseCase,
    ImportJDUseCase,
    ImportCapabilitySkillSnapshotUseCase,
    ImportPublishedJDFactUseCase,
    ImportReleaseUseCase,
    ModifyRelationUseCase,
    OpenGraphDraftUseCase,
    NormalizeJDUseCase,
    PublishGraphVersionUseCase,
    RebuildProjectionUseCase,
    ReviewMappingCandidateUseCase,
    ReviewDependencyCandidateUseCase,
    ResolveUnresolvedSkillUseCase,
    RollbackGraphVersionUseCase,
    UpdateAlgorithmConfigUseCase,
    UpsertJDUseCase,
)

__all__ = [name for name in globals() if name.endswith("UseCase")]
