from __future__ import annotations

from typing import Protocol

from app.domain.value_types import SerializedPayload


class AuthenticationQueries(Protocol):
    def authenticate(self, username: str) -> SerializedPayload | None: ...


class DocumentQueries(Protocol):
    def list_documents(self) -> list[SerializedPayload]: ...
    def document(self, document_id: str) -> SerializedPayload | None: ...
    def extraction(self, document_id: str) -> SerializedPayload | None: ...
    def normalization(self, document_id: str) -> SerializedPayload | None: ...
    def unresolved_items(self, status: str) -> list[SerializedPayload]: ...


class CatalogQueries(Protocol):
    def positions(self) -> list[SerializedPayload]: ...
    def integration_positions(self) -> list[SerializedPayload]: ...
    def integration_position_references(self) -> list[SerializedPayload]: ...
    def position(self, position_id: str) -> SerializedPayload | None: ...
    def skills(self) -> list[SerializedPayload]: ...
    def skill(self, skill_id: str) -> SerializedPayload | None: ...
    def category_tree(self, kind: str) -> list[SerializedPayload]: ...


class BuildQueries(Protocol):
    def build_job(self, job_id: int) -> SerializedPayload | None: ...
    def build_runs(self, position_id: str) -> list[SerializedPayload]: ...
    def build_run(self, run_id: int) -> SerializedPayload | None: ...
    def build_samples(self, run_id: int) -> list[SerializedPayload] | None: ...
    def publish_gate(self, run_id: int) -> SerializedPayload | None: ...


class GraphQueries(Protocol):
    def graph(self, position_id: str) -> SerializedPayload: ...
    def draft_graph(self, run_id: int) -> SerializedPayload | None: ...
    def relations(
        self, position_id: str, *, version_id: int | None, page: int,
        page_size: int, skill_id: str | None, category_code: str | None,
        importance_level: str | None, modality: str | None,
        min_weight: float | None, min_confidence: float | None,
    ) -> SerializedPayload | None: ...
    def relation_explanation(
        self, relation_id: int, version_id: int | None = None
    ) -> SerializedPayload | None: ...
    def visualization(self, position_id: str) -> SerializedPayload: ...


class PositionProfileQueries(Protocol):
    def position_profile(
        self, position_id: str, *, contract_version: str,
        graph_version_id: int | None = None, view: str = "published",
        draft_id: int | None = None,
    ) -> SerializedPayload | None: ...
    def skill_relations_batch(self, skill_ids: tuple[str, ...]) -> SerializedPayload: ...


class EvidenceQueries(Protocol):
    def relation_evidence(self, relation_id: int) -> list[SerializedPayload] | None: ...
    def aggregate_evidence(self, aggregate_id: int, kind: str) -> list[SerializedPayload] | None: ...
    def document_evidence(self, document_id: str) -> list[SerializedPayload]: ...


class ReviewQueries(Protocol):
    def review_tasks(
        self, *, page: int = 1, page_size: int = 20,
        status: str | None = None, risk_level: str | None = None,
        task_kind: str | None = None, build_run_id: int | None = None,
        statuses: tuple[str, ...] | None = None,
    ) -> SerializedPayload: ...
    def review_task(self, task_id: int) -> SerializedPayload | None: ...


class VersionQueries(Protocol):
    def versions(self, position_id: str) -> list[SerializedPayload]: ...
    def version(self, position_id: str, version_id: int) -> SerializedPayload | None: ...
    def version_diff(self, position_id: str, before_id: int, after_id: int) -> SerializedPayload | None: ...
    def evolution_events(
        self,
        position_id: str,
        before_id: int,
        after_id: int,
        event_type: str | None = None,
    ) -> SerializedPayload | None: ...
    def evolution_event(
        self, position_id: str, event_id: str
    ) -> SerializedPayload | None: ...


class InnovationQueries(Protocol):
    def change_impact(self, entity_type: str, entity_id: str) -> SerializedPayload | None: ...
    def dependency_events(self, entity_type: str, entity_id: str) -> list[SerializedPayload]: ...
    def build_watermark(self, build_run_id: int) -> SerializedPayload | None: ...
    def relation_claims(self, graph_version_id: int) -> list[SerializedPayload]: ...
    def mapping_candidates(self, status: str | None = None) -> list[SerializedPayload]: ...
    def dependency_analysis(self, build_run_id: int) -> SerializedPayload | None: ...
    def graph_projection(
        self, graph_version_id: int, projection_version: str | None = None
    ) -> SerializedPayload | None: ...


class KnowledgeGraphQueryService(
    AuthenticationQueries,
    DocumentQueries,
    CatalogQueries,
    BuildQueries,
    GraphQueries,
    PositionProfileQueries,
    EvidenceQueries,
    ReviewQueries,
    VersionQueries,
    InnovationQueries,
    Protocol,
):
    """Aggregate read boundary composed from independently replaceable query ports."""
