from enum import StrEnum


class ContractErrorCode(StrEnum):
    UNSUPPORTED_VERSION = "unsupported_contract_version"
    INVALID_EVIDENCE = "invalid_evidence"
    IDENTITY_MAPPING_REQUIRED = "identity_mapping_required"
    UPSTREAM_CONTRACT_ERROR = "upstream_contract_error"


class CVExtractionErrorCode(StrEnum):
    CV_FILE_TYPE_UNSUPPORTED = "CV_FILE_TYPE_UNSUPPORTED"
    CV_FILE_TOO_LARGE = "CV_FILE_TOO_LARGE"
    CV_FILE_MIME_MISMATCH = "CV_FILE_MIME_MISMATCH"
    CV_PDF_TEXT_EXTRACTION_FAILED = "CV_PDF_TEXT_EXTRACTION_FAILED"
    CV_DOCX_TEXT_EXTRACTION_FAILED = "CV_DOCX_TEXT_EXTRACTION_FAILED"
    CV_OCR_UNAVAILABLE = "CV_OCR_UNAVAILABLE"
    CV_OCR_FAILED = "CV_OCR_FAILED"
    CV_TEXT_EMPTY = "CV_TEXT_EMPTY"
    CV_NORMALIZATION_RESOURCE_MISSING = "CV_NORMALIZATION_RESOURCE_MISSING"
    CV_NORMALIZATION_VERSION_MISMATCH = "CV_NORMALIZATION_VERSION_MISMATCH"
    CV_TAXONOMY_VERSION_MISMATCH = "CV_TAXONOMY_VERSION_MISMATCH"
    CV_EXTRACTION_API_KEY_MISSING = "CV_EXTRACTION_API_KEY_MISSING"
    CV_EXTRACTION_AUTH_FAILED = "CV_EXTRACTION_AUTH_FAILED"
    CV_EXTRACTION_MODEL_NOT_AVAILABLE = "CV_EXTRACTION_MODEL_NOT_AVAILABLE"
    CV_EXTRACTION_RATE_LIMITED = "CV_EXTRACTION_RATE_LIMITED"
    CV_EXTRACTION_PROVIDER_TIMEOUT = "CV_EXTRACTION_PROVIDER_TIMEOUT"
    CV_EXTRACTION_PROVIDER_CONNECTION_FAILED = "CV_EXTRACTION_PROVIDER_CONNECTION_FAILED"
    CV_EXTRACTION_PROVIDER_INVALID_RESPONSE = "CV_EXTRACTION_PROVIDER_INVALID_RESPONSE"
    CV_EXTRACTION_PROVIDER_UNAVAILABLE = "CV_EXTRACTION_PROVIDER_UNAVAILABLE"
    CV_EXTRACTION_CONTRACT_INVALID = "CV_EXTRACTION_CONTRACT_INVALID"
    CV_EVIDENCE_ALIGNMENT_INVALID = "CV_EVIDENCE_ALIGNMENT_INVALID"
