"""Deterministic learning-asset catalog for the Learning Path chain.

This module is pure static data plus pure lookup logic:

- it never calls any LLM/AI API and introduces no external dependency;
- it never changes Matching, Gap Analysis, What-if deltas, Minimal Action
  Sets, route selection, ordering, dependencies, gains or costs;
- it only upgrades already-planned actions into concrete learning content
  (title / deliverable / acceptance criteria) and keeps the existing planner
  templates as the fallback whenever an asset is not configured, so every
  skill can still generate a path;
- every lookup is deterministic (normalized keys, no randomness).

Cost-model priority: ``estimated_hours`` produced by ``LearningRoutePlanner``
is always authoritative.  The optional ``estimated_hours`` stored here is
reference metadata only and is never applied over the planner cost model.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass


@dataclass(frozen=True)
class LearningAsset:
    """One concrete learning asset for a skill at a specific stage."""

    skill_ids: tuple[str, ...]
    names: tuple[str, ...]
    stage: str
    title: str
    deliverable: str
    acceptance_criteria: tuple[str, ...]
    estimated_hours: float | None = None
    resource_keywords: tuple[str, ...] = ()
    target_levels: tuple[str, ...] = ()


@dataclass(frozen=True)
class ResponsibilityActionTemplate:
    """Responsibility practice template used by the route planner."""

    name: str
    patterns: tuple[str, ...]
    deliverable: str
    acceptance_criteria: tuple[str, ...]
    base_hours: float


RESPONSIBILITY_ACTION_TEMPLATES = (
    ResponsibilityActionTemplate(
        "大模型后训练研究与实验验证",
        (
            "post-training", "后训练", "rlaif", "on-policy", "distillation",
            "rlhf", "dpo", "grpo", "sft",
        ),
        "完成一项后训练技术复现或小规模对比实验，提交可运行代码、实验配置、指标对比和业务适用性结论",
        ("代码与实验配置可复现", "至少包含一组基线与改进方案对比", "报告说明指标、结论和适用边界"),
        20.0,
    ),
    ResponsibilityActionTemplate(
        "Agentic AI 服务部署与性能工程",
        ("agentic", "agent", "智能体", "服务部署", "性能测试", "推理服务"),
        "完成一个 Agentic AI 服务的部署、压测和优化闭环，提交部署配置、压测脚本及优化前后对比报告",
        (
            "服务可重复部署并通过健康检查",
            "记录 QPS、p95 延迟、资源占用等核心指标",
            "至少完成一项有数据依据的性能优化",
        ),
        24.0,
    ),
    ResponsibilityActionTemplate(
        "大模型分布式训练工程",
        ("分布式训练", "megatron", "deepspeed", "ai infra", "并行策略", "训练框架", "训练稳定性"),
        "完成一次可复现的分布式训练实验，提交启动配置、并行策略、资源利用率和稳定性分析",
        ("训练任务可复现", "记录吞吐、显存或加速比等指标", "说明故障、瓶颈与优化结论"),
        24.0,
    ),
    ResponsibilityActionTemplate(
        "后训练数据构建与质量治理",
        ("sft 数据", "偏好数据", "数据治理", "数据清洗", "合成数据", "数据配比", "数据质量"),
        "构建一份可审计的训练数据样例集，提交数据规范、清洗规则、质量检查结果和版本记录",
        ("数据来源与处理过程可追溯", "包含明确的质量指标和异常样例", "数据版本及变更记录完整"),
        16.0,
    ),
    ResponsibilityActionTemplate(
        "大模型评测与质量保障",
        ("模型评估", "评测体系", "效果评估", "badcase", "效果验证", "评估体系"),
        "建立一套小规模模型评测基线，提交评测集、指标定义、运行脚本和结果分析",
        ("评测脚本可复现", "指标与岗位业务目标对应", "包含典型失败案例和改进建议"),
        16.0,
    ),
    ResponsibilityActionTemplate(
        "模型安全、对抗与风险控制",
        ("对抗防御", "幻觉检测", "安全对齐", "风险", "内容安全", "合规"),
        "完成一次模型风险专项验证，提交攻击或风险样例、检测规则、量化结果和缓解方案",
        ("风险样例与检测结果可复现", "给出覆盖率或误报漏报等量化指标", "缓解方案包含验证结果"),
        20.0,
    ),
    ResponsibilityActionTemplate(
        "业务需求挖掘与机会验证",
        ("挖掘发现", "潜在业务需求", "业务需求挖掘", "需求挖掘", "商机挖掘"),
        "完成一次业务需求挖掘与机会验证，提交需求洞察、潜在业务方向、可行性结论与验证记录",
        ("需求来源与推断过程可追溯", "给出潜在业务方向与可行性结论", "验证记录与复盘说明完整"),
        16.0,
    ),
)


def responsibility_action_template(text: str) -> ResponsibilityActionTemplate:
    lowered = text.casefold()
    for template in RESPONSIBILITY_ACTION_TEMPLATES:
        if any(pattern in lowered for pattern in template.patterns):
            return template
    concise = re.split(r"[，,；;。]", text, maxsplit=1)[0].strip()
    concise = re.sub(r"^(?:负责|参与|主导|承担|协助)", "", concise).strip()
    name = f"{concise[:32]}综合实践" if concise else "岗位职责综合实践"
    return ResponsibilityActionTemplate(
        name,
        (),
        f"围绕“{text}”完成一项可运行或可复现的实践交付物，并形成指标记录和复盘说明",
        ("交付物可运行或可复现", "记录输入、过程、结果和关键指标", "形成与岗位职责对应的证据说明"),
        16.0,
    )


# ── First-batch learning assets for high-frequency graph skills ─────────────

_LEARNING_ASSETS = (
    # Python
    LearningAsset(
        ("skill_python", "python", "python3"),
        ("Python",),
        "foundation",
        "Python 基础语法与核心编程",
        "完成 Python 基础语法、数据结构、函数与文件处理练习，提交可运行的练习代码与运行记录",
        ("练习代码可复现", "覆盖变量、流程控制、函数与常用数据结构", "保留练习与运行记录"),
        8.0,
        ("Python 官方教程", "PEP 8", "pytest"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_python", "python", "python3"),
        ("Python",),
        "proficiency",
        "Python 工程化能力提升",
        "完成一个包含模块化、异常处理、单元测试和命令行入口的 Python 工程，"
        "提交可运行项目与测试结果",
        ("项目可运行并可通过测试", "代码结构清晰且包含异常处理", "保留测试与运行记录"),
        12.0,
        ("pytest", "虚拟环境", "类型注解"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_python", "python", "python3"),
        ("Python",),
        "project",
        "Python 工程实践项目",
        "完成一个面向真实任务的 Python 项目，提交可运行源码、测试、使用说明和指标记录",
        ("交付物完整且可运行", "验收标准明确", "形成指标记录与复盘说明"),
        24.0,
        ("项目工程化", "测试覆盖", "性能分析"),
    ),
    LearningAsset(
        ("skill_python", "python", "python3"),
        ("Python",),
        "ownership",
        "独立负责 Python 服务模块开发",
        "独立负责一个 Python 服务模块从设计、实现到交付，提交设计说明、实现、测试与线上运行证据",
        ("独立负责范围可核验", "模块交付物可运行且可维护", "成果与影响可溯源"),
        32.0,
        ("服务开发", "线上运维", "代码评审"),
    ),
    # PyTorch
    LearningAsset(
        ("skill_pytorch", "pytorch", "torch"),
        ("PyTorch",),
        "foundation",
        "PyTorch 基础张量运算与自动求导",
        "完成 PyTorch 张量运算、数据加载与自动求导练习，提交可运行练习代码和运行结果说明",
        ("练习代码可复现", "覆盖张量、DataLoader 与 autograd", "保留练习与运行记录"),
        8.0,
        ("PyTorch 官方教程", "Tensor", "autograd"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_pytorch", "pytorch", "torch"),
        ("PyTorch",),
        "proficiency",
        "PyTorch 训练管线搭建与模型训练",
        "搭建一条包含数据加载、模型定义、训练循环、验证与断点保存的 PyTorch 训练管线，"
        "提交可运行脚本和训练指标记录",
        ("训练管线可复现", "记录 loss、准确率等训练指标", "保存模型权重与断点"),
        12.0,
        ("训练循环", "模型保存", "训练日志"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_pytorch", "pytorch", "torch"),
        ("PyTorch",),
        "project",
        "PyTorch 模型训练与调优实践",
        "完成一次基于 PyTorch 的模型训练与调优实践，"
        "提交可运行训练脚本、数据管线、指标记录与调优结论",
        ("训练脚本与数据管线可复现", "记录基线、调优配置与指标对比", "形成可核验的调优结论"),
        24.0,
        ("模型训练", "超参数调优", "训练监控"),
    ),
    LearningAsset(
        ("skill_pytorch", "pytorch", "torch"),
        ("PyTorch",),
        "ownership",
        "独立负责 PyTorch 训练工程",
        "独立负责一个 PyTorch 训练工程从数据准备到部署交付，提交工程代码、训练报告与线上验证结果",
        ("独立负责范围可核验", "训练工程可复现并可持续迭代", "成果指标与影响可溯源"),
        32.0,
        ("训练工程", "部署推理", "资源优化"),
    ),
    # Docker
    LearningAsset(
        ("skill_docker", "docker", "容器"),
        ("Docker",),
        "foundation",
        "Docker 容器基础与镜像构建",
        "完成 Docker 安装、镜像构建、容器运行与数据卷练习，提交可复现的 Dockerfile 与运行记录",
        ("镜像可构建并可运行", "Dockerfile 分层清晰", "保留构建与运行记录"),
        8.0,
        ("Docker 官方文档", "Dockerfile", "docker compose"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_docker", "docker", "容器"),
        ("Docker",),
        "proficiency",
        "Docker 容器编排与多服务部署",
        "使用 Compose 编排包含应用、数据库与缓存的多服务环境，提交编排文件、健康检查和启动说明",
        ("多服务环境可一键启动", "服务健康检查通过", "端口、网络与数据卷配置可复现"),
        12.0,
        ("docker compose", "网络配置", "健康检查"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_docker", "docker", "容器"),
        ("Docker",),
        "project",
        "Docker 容器化部署实践",
        "完成一个应用的容器化部署，提交镜像、编排配置、部署步骤和验证结果",
        ("部署步骤可复现", "镜像与编排配置完整", "形成部署验证与指标记录"),
        24.0,
        ("容器化部署", "镜像优化", "部署验证"),
    ),
    LearningAsset(
        ("skill_docker", "docker", "容器"),
        ("Docker",),
        "ownership",
        "独立负责容器化平台建设",
        "独立负责一个应用的容器化改造与交付，提交设计、镜像、编排、监控与线上运行证据",
        ("独立负责范围可核验", "容器化方案可维护可升级", "运行稳定性与影响可溯源"),
        32.0,
        ("容器化治理", "监控告警", "发布流程"),
    ),
    # FastAPI
    LearningAsset(
        ("skill_fastapi", "fastapi"),
        ("FastAPI",),
        "foundation",
        "FastAPI 基础接口开发",
        "完成 FastAPI 路由、请求校验与响应模型练习，提交可运行接口代码和调用示例",
        ("接口可运行", "覆盖路径参数、查询参数与请求体校验", "保留接口调用记录"),
        8.0,
        ("FastAPI 官方文档", "Pydantic", "Swagger"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_fastapi", "fastapi"),
        ("FastAPI",),
        "proficiency",
        "FastAPI 工程化接口与异步服务",
        "搭建一个包含分层结构、依赖注入、错误处理与单元测试的 FastAPI 服务，"
        "提交可运行项目与测试结果",
        ("服务可启动并通过测试", "接口文档与错误处理完整", "保留性能与调用记录"),
        12.0,
        ("依赖注入", "异步接口", "pytest"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_fastapi", "fastapi"),
        ("FastAPI",),
        "project",
        "FastAPI 服务开发与部署实践",
        "完成一个 FastAPI 服务的开发、测试与部署，提交源码、接口文档、部署配置和验证记录",
        ("服务可运行并可通过接口验收", "包含测试与部署说明", "形成指标记录与复盘说明"),
        24.0,
        ("服务开发", "接口测试", "部署上线"),
    ),
    LearningAsset(
        ("skill_fastapi", "fastapi"),
        ("FastAPI",),
        "ownership",
        "独立负责 FastAPI 服务交付",
        "独立负责一个 FastAPI 服务从设计到上线交付，提交设计、实现、测试、监控与线上证据",
        ("独立负责范围可核验", "服务可运维可监控", "交付影响与指标可溯源"),
        32.0,
        ("服务交付", "线上监控", "容量评估"),
    ),
    # Transformer
    LearningAsset(
        ("skill_transformer", "transformer", "transformers", "变换器"),
        ("Transformer", "变换器神经网络架构"),
        "foundation",
        "Transformer 结构与预训练基础",
        "完成 Transformer 自注意力、位置编码与编码器-解码器结构练习，提交可运行示例和结构说明",
        ("示例代码可复现", "覆盖注意力、位置编码与残差连接", "能说明各模块作用"),
        8.0,
        ("Attention Is All You Need", "Hugging Face 文档", "自注意力"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_transformer", "transformer", "transformers", "变换器"),
        ("Transformer", "变换器神经网络架构"),
        "proficiency",
        "Transformer 微调与推理部署",
        "使用预训练 Transformer 完成一次微调与推理实践，提交训练脚本、评估结果和推理示例",
        ("微调与推理可复现", "记录评估指标与资源消耗", "推理示例可运行"),
        12.0,
        ("微调", "推理", "评估指标"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_transformer", "transformer", "transformers", "变换器"),
        ("Transformer", "变换器神经网络架构"),
        "project",
        "Transformer 模型应用实践",
        "完成一个基于 Transformer 的实际应用项目，提交数据处理、训练/微调、评估与部署说明",
        ("项目可复现", "指标与业务目标对应", "包含失败案例与改进建议"),
        24.0,
        ("模型应用", "效果评估", "部署验证"),
    ),
    LearningAsset(
        ("skill_transformer", "transformer", "transformers", "变换器"),
        ("Transformer", "变换器神经网络架构"),
        "ownership",
        "独立负责 Transformer 模型工程",
        "独立负责一个 Transformer 模型从数据到上线交付，提交工程代码、评估报告与线上验证",
        ("独立负责范围可核验", "模型工程可持续迭代", "效果与影响可溯源"),
        32.0,
        ("模型工程", "效果治理", "线上验证"),
    ),
    # RAG
    LearningAsset(
        ("skill_rag", "rag", "检索增强"),
        ("RAG", "检索增强生成"),
        "foundation",
        "RAG 基础组件与检索概念",
        "完成文档切分、向量化、检索与提示拼装练习，提交可运行的 RAG 最小链路代码",
        ("最小链路可运行", "覆盖切分、检索与生成三个环节", "保留示例文档与检索记录"),
        8.0,
        ("向量检索", "文档切分", "提示工程"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_rag", "rag", "检索增强"),
        ("RAG", "检索增强生成"),
        "proficiency",
        "RAG 检索管线与问答效果调优",
        "搭建并调优一套 RAG 问答管线，提交索引构建、检索策略、评估集与效果对比",
        ("管线可复现", "检索与问答指标可量化", "包含至少一组策略对比"),
        12.0,
        ("检索评估", "重排序", "效果调优"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_rag", "rag", "检索增强"),
        ("RAG", "检索增强生成"),
        "project",
        "RAG 检索增强生成系统实践",
        "完成一个可用的 RAG 系统，提交数据接入、索引、检索、生成与评估说明及运行证据",
        ("系统可运行并通过验收", "数据与评估流程可追溯", "形成效果指标与复盘说明"),
        24.0,
        ("RAG 系统", "评估集", "端到端验证"),
    ),
    LearningAsset(
        ("skill_rag", "rag", "检索增强"),
        ("RAG", "检索增强生成"),
        "ownership",
        "独立负责 RAG 系统建设与优化",
        "独立负责一个 RAG 系统从选型、建设到线上优化，提交架构、评估、监控与线上证据",
        ("独立负责范围可核验", "系统可监控可回滚", "效果与业务影响可溯源"),
        32.0,
        ("系统建设", "线上监控", "效果治理"),
    ),
    # Agent
    LearningAsset(
        ("skill_agent", "agent", "agentic", "智能体"),
        ("Agent", "AI Agent", "智能体"),
        "foundation",
        "AI Agent 基础概念与工具调用",
        "完成 Agent 角色设定、工具调用与多轮交互练习，提交可运行的 Agent 示例和运行记录",
        ("示例可运行", "覆盖工具调用与结果回传", "保留交互与运行记录"),
        8.0,
        ("Agent 框架文档", "工具调用", "提示词设计"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_agent", "agent", "agentic", "智能体"),
        ("Agent", "AI Agent", "智能体"),
        "proficiency",
        "Agent 规划、记忆与工具编排",
        "实现一个具备规划、记忆和多个工具编排的 Agent，提交任务流程、调用日志和结果评估",
        ("任务流程可复现", "规划与记忆机制可解释", "记录成功率与失败案例"),
        12.0,
        ("任务规划", "记忆管理", "工具编排"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_agent", "agent", "agentic", "智能体"),
        ("Agent", "AI Agent", "智能体"),
        "project",
        "AI Agent 应用开发实践",
        "完成一个面向真实任务的 Agent 应用，提交设计、实现、评测与运行证据",
        ("应用可运行并通过验收", "评测指标与业务目标对应", "形成失败案例与改进建议"),
        24.0,
        ("Agent 应用", "效果评测", "稳定性"),
    ),
    LearningAsset(
        ("skill_agent", "agent", "agentic", "智能体"),
        ("Agent", "AI Agent", "智能体"),
        "ownership",
        "独立负责 Agent 产品能力建设",
        "独立负责一个 Agent 能力从设计到线上交付，提交架构、评测、监控与业务影响证据",
        ("独立负责范围可核验", "能力可评测可监控", "业务影响可溯源"),
        32.0,
        ("产品能力", "线上评测", "迭代治理"),
    ),
    # MySQL
    LearningAsset(
        ("skill_mysql", "mysql"),
        ("MySQL",),
        "foundation",
        "MySQL 基础 SQL 与数据建模",
        "完成建表、增删改查、索引与简单关联查询练习，提交可复现的 SQL 脚本和运行结果",
        ("SQL 脚本可复现", "覆盖常用查询与索引使用", "保留执行与结果记录"),
        8.0,
        ("MySQL 官方文档", "SQL 练习", "ER 设计"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_mysql", "mysql"),
        ("MySQL",),
        "proficiency",
        "MySQL 索引优化与事务设计",
        "完成一个包含事务、索引优化与慢查询分析的数据库实践，提交表结构、执行计划和优化前后对比",
        ("优化过程可复现", "记录执行计划与耗时对比", "事务与隔离级别说明完整"),
        12.0,
        ("执行计划", "慢查询", "事务隔离"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_mysql", "mysql"),
        ("MySQL",),
        "project",
        "MySQL 数据库设计与优化实践",
        "完成一个业务场景的数据库设计与优化，提交模型设计、索引方案、压测结果与调优结论",
        ("设计方案可复现", "包含容量与性能评估", "形成优化指标与复盘说明"),
        24.0,
        ("数据库设计", "性能压测", "容量评估"),
    ),
    LearningAsset(
        ("skill_mysql", "mysql"),
        ("MySQL",),
        "ownership",
        "独立负责 MySQL 数据架构优化",
        "独立负责一个 MySQL 数据架构的优化与治理，提交架构方案、监控、变更与线上验证证据",
        ("独立负责范围可核验", "变更可回滚可审计", "性能与稳定性影响可溯源"),
        32.0,
        ("架构治理", "监控告警", "变更管理"),
    ),
    # Redis
    LearningAsset(
        ("skill_redis", "redis"),
        ("Redis",),
        "foundation",
        "Redis 基础数据结构与命令",
        "完成 Redis 常用数据结构、过期策略与持久化练习，提交可复现命令脚本和运行说明",
        ("命令脚本可复现", "覆盖常用数据结构与过期策略", "保留运行与说明记录"),
        8.0,
        ("Redis 官方文档", "数据结构", "持久化"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_redis", "redis"),
        ("Redis",),
        "proficiency",
        "Redis 高可用与缓存策略",
        "完成一个含缓存策略、淘汰策略与故障演练的 Redis 实践，提交配置、脚本与结果对比",
        ("配置与脚本可复现", "记录命中率、延迟与故障恢复表现", "缓存一致性说明完整"),
        12.0,
        ("缓存策略", "高可用", "故障演练"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_redis", "redis"),
        ("Redis",),
        "project",
        "Redis 缓存与高并发实践",
        "完成一个高并发场景下的 Redis 缓存实践，提交架构、压测、监控与优化结论",
        ("架构与压测可复现", "记录吞吐、延迟与资源指标", "形成缓存优化与复盘说明"),
        24.0,
        ("高并发缓存", "压测", "监控"),
    ),
    LearningAsset(
        ("skill_redis", "redis"),
        ("Redis",),
        "ownership",
        "独立负责 Redis 基础设施与治理",
        "独立负责 Redis 基础设施的规划、治理与故障处置，提交架构、监控、预案与线上证据",
        ("独立负责范围可核验", "监控与预案完整", "稳定性影响可溯源"),
        32.0,
        ("基础设施", "容量规划", "故障预案"),
    ),
    # Linux
    LearningAsset(
        ("skill_linux", "linux"),
        ("Linux",),
        "foundation",
        "Linux 基础命令与文件系统",
        "完成 Linux 常用命令、文件权限、进程与网络排查练习，提交命令清单和操作记录",
        ("命令操作可复现", "覆盖文件、进程与网络排查", "保留操作与结果记录"),
        8.0,
        ("Linux 文档", "Shell 基础", "权限管理"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_linux", "linux"),
        ("Linux",),
        "proficiency",
        "Linux 脚本自动化与系统管理",
        "完成一个包含 Shell 脚本、定时任务与服务管理的自动化实践，提交脚本、配置与验证结果",
        ("脚本可复现", "覆盖日志、定时任务与服务管理", "验证结果记录完整"),
        12.0,
        ("Shell 脚本", "systemd", "日志分析"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_linux", "linux"),
        ("Linux",),
        "project",
        "Linux 运维与自动化实践",
        "完成一个 Linux 环境的运维自动化项目，提交脚本、部署方案、监控与验证记录",
        ("自动化方案可复现", "包含监控与异常处理", "形成运维指标与复盘说明"),
        24.0,
        ("运维自动化", "监控", "异常处置"),
    ),
    LearningAsset(
        ("skill_linux", "linux"),
        ("Linux",),
        "ownership",
        "独立负责 Linux 环境与运维治理",
        "独立负责 Linux 环境的治理与稳定性保障，提交规范、监控、预案与线上证据",
        ("独立负责范围可核验", "规范与预案完整", "稳定性影响可溯源"),
        32.0,
        ("环境治理", "容量与性能", "变更管理"),
    ),
    # Git
    LearningAsset(
        ("skill_git", "git"),
        ("Git",),
        "foundation",
        "Git 基础命令与工作流",
        "完成 Git 提交、分支、合并与远程协作练习，提交仓库操作记录和说明",
        ("操作记录可复现", "覆盖提交、分支与合并", "远程协作流程说明完整"),
        8.0,
        ("Git 官方文档", "分支管理", "远程仓库"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_git", "git"),
        ("Git",),
        "proficiency",
        "Git 分支协作与冲突解决",
        "在一个协作仓库中完成分支策略、代码评审与冲突解决实践，提交协作记录与冲突处理说明",
        ("协作流程可复现", "冲突解决过程可追溯", "分支与评审规范完整"),
        12.0,
        ("分支策略", "代码评审", "冲突处理"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_git", "git"),
        ("Git",),
        "project",
        "Git 协作与持续集成实践",
        "完成一个结合 Git 工作流与持续集成的项目实践，提交仓库规范、流水线配置与验证记录",
        ("流水线可运行", "仓库与提交规范完整", "形成协作与发布复盘说明"),
        24.0,
        ("持续集成", "仓库治理", "发布流程"),
    ),
    LearningAsset(
        ("skill_git", "git"),
        ("Git",),
        "ownership",
        "独立负责代码工程协作规范",
        "独立负责一个代码仓库的工程协作治理，提交规范、评审流程、自动化与线上证据",
        ("独立负责范围可核验", "规范与自动化可执行", "协作效率影响可溯源"),
        32.0,
        ("工程治理", "评审流程", "自动化"),
    ),
    # CUDA
    LearningAsset(
        ("skill_cuda", "cuda"),
        ("CUDA",),
        "foundation",
        "CUDA 基础编程模型与线程结构",
        "完成 CUDA 环境配置、线程格/块结构与简单核函数练习，提交可编译运行代码和性能说明",
        ("代码可编译运行", "覆盖线程组织与内存访问", "记录运行与性能结果"),
        8.0,
        ("CUDA 官方文档", "线程模型", "nvcc"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_cuda", "cuda"),
        ("CUDA",),
        "proficiency",
        "CUDA 核函数编写与性能分析",
        "完成一个含内存优化与性能分析的 CUDA 实践，提交核函数、分析工具输出与优化对比",
        ("优化过程可复现", "记录访存与计算性能指标", "包含至少一组优化对比"),
        12.0,
        ("内存优化", "Nsight", "性能分析"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_cuda", "cuda"),
        ("CUDA",),
        "project",
        "CUDA 并行计算实践",
        "完成一个面向真实计算的 CUDA 加速实践，提交源码、编译说明、性能对比与验证结果",
        ("加速代码可复现", "记录加速比与正确性验证", "形成性能与复盘说明"),
        24.0,
        ("并行计算", "加速比", "正确性验证"),
    ),
    LearningAsset(
        ("skill_cuda", "cuda"),
        ("CUDA",),
        "ownership",
        "独立负责 CUDA 加速模块开发",
        "独立负责一个 CUDA 加速模块从设计到交付，提交设计、实现、性能报告与线上验证",
        ("独立负责范围可核验", "模块可复现可维护", "性能与影响可溯源"),
        32.0,
        ("加速模块", "性能工程", "交付验证"),
    ),
    # LoRA
    LearningAsset(
        ("skill_lora", "lora"),
        ("LoRA",),
        "foundation",
        "LoRA 原理与参数高效微调基础",
        "完成 LoRA 原理、低秩分解与参数高效微调概念练习，提交可运行的微调配置示例与说明",
        ("示例可复现", "理解低秩适配与基座冻结原理", "保留配置与运行记录"),
        8.0,
        ("LoRA 论文", "PEFT", "微调配置"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_lora", "lora"),
        ("LoRA",),
        "proficiency",
        "LoRA 微调训练与评估",
        "完成一次 LoRA 微调与评估实践，提交训练脚本、数据准备、指标对比与推理示例",
        ("微调与评估可复现", "记录训练与评估指标", "包含基座与 LoRA 对比"),
        12.0,
        ("PEFT", "训练脚本", "效果评估"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_lora", "lora"),
        ("LoRA",),
        "project",
        "LoRA 模型微调实践",
        "完成一个面向业务数据的 LoRA 微调项目，提交数据管线、训练配置、评估集与结果分析",
        ("项目可复现", "指标与业务目标对应", "形成失败案例与改进建议"),
        24.0,
        ("业务微调", "评估集", "效果治理"),
    ),
    LearningAsset(
        ("skill_lora", "lora"),
        ("LoRA",),
        "ownership",
        "独立负责 LoRA 微调工程",
        "独立负责一个 LoRA 微调能力从数据到交付，提交工程代码、评估报告与线上验证",
        ("独立负责范围可核验", "微调工程可迭代", "效果与影响可溯源"),
        32.0,
        ("微调工程", "线上验证", "迭代治理"),
    ),
    # TensorRT-LLM
    LearningAsset(
        ("skill_tensorrt_llm", "tensorrt-llm", "tensorrt_llm"),
        ("TensorRT-LLM",),
        "foundation",
        "TensorRT-LLM 基础与模型转换",
        "完成 TensorRT-LLM 环境搭建与模型权重转换练习，提交转换配置、构建日志与运行说明",
        ("转换流程可复现", "引擎构建成功并可加载", "记录版本与构建参数"),
        8.0,
        ("TensorRT-LLM 文档", "模型转换", "引擎构建"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_tensorrt_llm", "tensorrt-llm", "tensorrt_llm"),
        ("TensorRT-LLM",),
        "proficiency",
        "TensorRT-LLM 引擎构建与优化",
        "完成 TensorRT-LLM 引擎构建、量化与推理参数优化，提交配置、基准测试与对比结果",
        ("引擎构建可复现", "记录延迟、吞吐与显存指标", "包含至少一组优化对比"),
        12.0,
        ("量化", "基准测试", "显存优化"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_tensorrt_llm", "tensorrt-llm", "tensorrt_llm"),
        ("TensorRT-LLM",),
        "project",
        "TensorRT-LLM 推理加速实践",
        "完成一个 TensorRT-LLM 推理加速实践，提交模型转换、引擎配置、压测与上线验证",
        ("加速方案可复现", "记录性能与正确性验证", "形成上线与复盘说明"),
        24.0,
        ("推理加速", "压测", "上线验证"),
    ),
    LearningAsset(
        ("skill_tensorrt_llm", "tensorrt-llm", "tensorrt_llm"),
        ("TensorRT-LLM",),
        "ownership",
        "独立负责 TensorRT-LLM 推理优化",
        "独立负责 TensorRT-LLM 推理优化从选型到交付，提交方案、基准、监控与线上证据",
        ("独立负责范围可核验", "优化方案可持续维护", "性能影响可溯源"),
        32.0,
        ("推理优化", "基准治理", "线上监控"),
    ),
    # vLLM
    LearningAsset(
        ("skill_vllm", "vllm"),
        ("vLLM",),
        "foundation",
        "vLLM 推理引擎基础",
        "完成 vLLM 安装、模型加载与基础推理练习，提交启动配置、推理示例与运行记录",
        ("推理示例可运行", "理解 PagedAttention 与连续批处理", "保留启动与运行记录"),
        8.0,
        ("vLLM 文档", "推理服务", "启动配置"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_vllm", "vllm"),
        ("vLLM",),
        "proficiency",
        "vLLM 服务部署与性能调优",
        "完成 vLLM 服务部署、并发配置与性能调优，提交服务配置、压测脚本与指标对比",
        ("服务可重复部署", "记录吞吐、延迟与显存指标", "包含至少一组调优对比"),
        12.0,
        ("OpenAI 兼容接口", "压测", "显存管理"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_vllm", "vllm"),
        ("vLLM",),
        "project",
        "vLLM 推理服务实践",
        "完成一个 vLLM 推理服务的部署与优化实践，提交部署方案、压测、监控与验证结果",
        ("服务可运行并通过验收", "性能与容量评估完整", "形成指标与复盘说明"),
        24.0,
        ("推理服务", "容量评估", "监控"),
    ),
    LearningAsset(
        ("skill_vllm", "vllm"),
        ("vLLM",),
        "ownership",
        "独立负责 vLLM 推理平台",
        "独立负责 vLLM 推理平台从建设到线上治理，提交架构、监控、容量规划与线上证据",
        ("独立负责范围可核验", "平台可监控可扩容", "稳定性与影响可溯源"),
        32.0,
        ("推理平台", "容量规划", "线上治理"),
    ),
    # OpenCV
    LearningAsset(
        ("skill_opencv", "opencv"),
        ("OpenCV",),
        "foundation",
        "OpenCV 图像处理基础",
        "完成 OpenCV 图像读写、滤波、几何变换与颜色空间练习，提交可运行代码与效果说明",
        ("代码可复现", "覆盖常用图像处理操作", "保留输入输出示例"),
        8.0,
        ("OpenCV 文档", "图像处理", "示例代码"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_opencv", "opencv"),
        ("OpenCV",),
        "proficiency",
        "OpenCV 视觉管线开发",
        "完成一个包含检测、跟踪或特征处理的视觉管线，提交管线代码、参数说明与结果评估",
        ("管线可复现", "记录处理耗时与准确率", "参数与边界说明完整"),
        12.0,
        ("目标检测", "特征提取", "管线优化"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_opencv", "opencv"),
        ("OpenCV",),
        "project",
        "OpenCV 视觉应用实践",
        "完成一个面向真实场景的 OpenCV 视觉应用，提交数据、处理流程、评估与运行证据",
        ("应用可运行并通过验收", "评估指标与业务目标对应", "形成复盘与改进说明"),
        24.0,
        ("视觉应用", "效果评估", "部署验证"),
    ),
    LearningAsset(
        ("skill_opencv", "opencv"),
        ("OpenCV",),
        "ownership",
        "独立负责视觉处理模块",
        "独立负责一个视觉处理模块从设计到交付，提交设计、实现、性能与线上验证",
        ("独立负责范围可核验", "模块可维护可复用", "效果与影响可溯源"),
        32.0,
        ("视觉模块", "性能工程", "交付验证"),
    ),
    # Milvus
    LearningAsset(
        ("skill_milvus", "milvus"),
        ("Milvus",),
        "foundation",
        "Milvus 向量数据库基础",
        "完成 Milvus 部署、集合创建与向量写入检索练习，提交配置、示例与运行记录",
        ("示例可复现", "理解集合、分区与索引概念", "保留运行记录"),
        8.0,
        ("Milvus 文档", "向量检索", "集合管理"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_milvus", "milvus"),
        ("Milvus",),
        "proficiency",
        "Milvus 索引与检索调优",
        "完成 Milvus 索引选型、检索参数与性能调优实践，提交索引配置、基准测试与对比",
        ("调优过程可复现", "记录召回率、延迟与吞吐", "包含至少一组索引对比"),
        12.0,
        ("索引选型", "召回评估", "性能基准"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_milvus", "milvus"),
        ("Milvus",),
        "project",
        "Milvus 检索系统实践",
        "完成一个基于 Milvus 的向量检索系统，提交数据接入、索引、检索服务与效果评估",
        ("系统可运行并通过验收", "检索效果与性能可量化", "形成指标与复盘说明"),
        24.0,
        ("检索系统", "效果评估", "容量评估"),
    ),
    LearningAsset(
        ("skill_milvus", "milvus"),
        ("Milvus",),
        "ownership",
        "独立负责向量检索平台",
        "独立负责向量检索平台从建设到线上治理，提交架构、监控、容量与线上证据",
        ("独立负责范围可核验", "平台可监控可扩容", "稳定性与影响可溯源"),
        32.0,
        ("向量平台", "容量规划", "线上治理"),
    ),
    # LangGraph
    LearningAsset(
        ("skill_langgraph", "langgraph"),
        ("LangGraph",),
        "foundation",
        "LangGraph 图编排基础",
        "完成 LangGraph 节点、边与状态流转练习，提交可运行的图示例与说明",
        ("示例可复现", "理解状态图与节点编排", "保留运行记录"),
        8.0,
        ("LangGraph 文档", "状态图", "节点编排"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_langgraph", "langgraph"),
        ("LangGraph",),
        "proficiency",
        "LangGraph Agent 工作流开发",
        "实现一个含工具调用、条件分支与循环的 LangGraph 工作流，提交流程、日志与结果评估",
        ("工作流可复现", "分支与循环逻辑可解释", "记录成功与失败案例"),
        12.0,
        ("Agent 工作流", "条件分支", "工具调用"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_langgraph", "langgraph"),
        ("LangGraph",),
        "project",
        "LangGraph 应用实践",
        "完成一个面向真实任务的 LangGraph 应用，提交设计、实现、评测与运行证据",
        ("应用可运行并通过验收", "评测指标与业务目标对应", "形成失败案例与改进建议"),
        24.0,
        ("Agent 应用", "效果评测", "稳定性"),
    ),
    LearningAsset(
        ("skill_langgraph", "langgraph"),
        ("LangGraph",),
        "ownership",
        "独立负责 Agent 工作流平台",
        "独立负责基于 LangGraph 的工作流能力从设计到交付，提交架构、评测、监控与线上证据",
        ("独立负责范围可核验", "工作流可评测可监控", "业务影响可溯源"),
        32.0,
        ("工作流平台", "线上评测", "迭代治理"),
    ),
    # Kubernetes
    LearningAsset(
        ("skill_kubernetes", "kubernetes", "k8s"),
        ("Kubernetes", "K8s"),
        "foundation",
        "Kubernetes 基础与 Pod 编排",
        "完成 Kubernetes 集群基础、Pod、Deployment 与服务暴露练习，提交 YAML 配置与运行记录",
        ("配置可复现", "理解 Pod、Deployment 与 Service", "保留运行记录"),
        8.0,
        ("Kubernetes 文档", "YAML 编排", "kubectl"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_kubernetes", "kubernetes", "k8s"),
        ("Kubernetes", "K8s"),
        "proficiency",
        "Kubernetes 服务部署与运维",
        "完成一个应用的 Kubernetes 部署、滚动更新与故障排查，提交清单、监控与验证结果",
        ("部署流程可复现", "滚动更新与回滚可验证", "排查与监控记录完整"),
        12.0,
        ("滚动更新", "故障排查", "监控告警"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_kubernetes", "kubernetes", "k8s"),
        ("Kubernetes", "K8s"),
        "project",
        "Kubernetes 平台实践",
        "完成一个 Kubernetes 平台化部署实践，提交命名空间、资源限制、灰度与验证方案",
        ("平台方案可复现", "资源与安全边界明确", "形成指标与复盘说明"),
        24.0,
        ("平台化", "资源治理", "灰度发布"),
    ),
    LearningAsset(
        ("skill_kubernetes", "kubernetes", "k8s"),
        ("Kubernetes", "K8s"),
        "ownership",
        "独立负责 Kubernetes 基础设施",
        "独立负责 Kubernetes 基础设施的规划与治理，提交架构、监控、预案与线上证据",
        ("独立负责范围可核验", "监控与预案完整", "稳定性影响可溯源"),
        32.0,
        ("基础设施", "容量规划", "故障预案"),
    ),
    # Flink
    LearningAsset(
        ("skill_flink", "flink"),
        ("Flink",),
        "foundation",
        "Flink 流处理基础",
        "完成 Flink 环境与 DataStream 基础练习，提交可运行的流处理作业与说明",
        ("作业可运行", "理解时间、窗口与状态概念", "保留运行记录"),
        8.0,
        ("Flink 文档", "DataStream", "窗口"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_flink", "flink"),
        ("Flink",),
        "proficiency",
        "Flink 作业开发与调优",
        "完成一个含窗口、状态与检查点的 Flink 作业，提交代码、并行度与调优结果",
        ("作业可复现", "记录吞吐、延迟与背压指标", "包含至少一组调优对比"),
        12.0,
        ("状态管理", "检查点", "背压调优"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_flink", "flink"),
        ("Flink",),
        "project",
        "Flink 实时计算实践",
        "完成一个面向业务场景的 Flink 实时计算实践，提交数据接入、作业、监控与验证",
        ("作业可上线并通过验收", "指标与业务目标对应", "形成指标与复盘说明"),
        24.0,
        ("实时计算", "数据接入", "监控验证"),
    ),
    LearningAsset(
        ("skill_flink", "flink"),
        ("Flink",),
        "ownership",
        "独立负责 Flink 实时平台",
        "独立负责 Flink 实时计算能力从建设到治理，提交架构、监控、容量与线上证据",
        ("独立负责范围可核验", "平台可监控可扩展", "稳定性影响可溯源"),
        32.0,
        ("实时平台", "容量规划", "线上治理"),
    ),
    # Spark
    LearningAsset(
        ("skill_spark", "spark"),
        ("Spark",),
        "foundation",
        "Spark 基础与 RDD/DataFrame",
        "完成 Spark 环境与 RDD/DataFrame 基础练习，提交可运行的批处理作业与说明",
        ("作业可运行", "理解 RDD、DataFrame 与分区", "保留运行记录"),
        8.0,
        ("Spark 文档", "DataFrame", "分区"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_spark", "spark"),
        ("Spark",),
        "proficiency",
        "Spark 数据处理与调优",
        "完成一个 Spark 数据处理作业的开发与调优，提交代码、执行计划与性能对比",
        ("作业可复现", "记录执行时间与资源指标", "包含至少一组调优对比"),
        12.0,
        ("执行计划", "Shuffle 调优", "资源管理"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_spark", "spark"),
        ("Spark",),
        "project",
        "Spark 数据处理实践",
        "完成一个面向业务数据的 Spark 处理实践，提交数据管线、作业、验证与结果分析",
        ("管线可复现", "数据质量与结果可验证", "形成指标与复盘说明"),
        24.0,
        ("数据管线", "数据质量", "批量处理"),
    ),
    LearningAsset(
        ("skill_spark", "spark"),
        ("Spark",),
        "ownership",
        "独立负责 Spark 数据平台",
        "独立负责 Spark 数据处理能力从建设到治理，提交架构、调度、监控与线上证据",
        ("独立负责范围可核验", "平台可监控可扩展", "稳定性影响可溯源"),
        32.0,
        ("数据平台", "调度治理", "线上监控"),
    ),
    # ONNX
    LearningAsset(
        ("skill_onnx", "onnx"),
        ("ONNX",),
        "foundation",
        "ONNX 模型转换基础",
        "完成模型导出 ONNX、算子检查与基础推理练习，提交导出配置、检查报告与运行记录",
        ("导出流程可复现", "模型可加载并推理", "记录算子与兼容性问题"),
        8.0,
        ("ONNX 文档", "模型导出", "算子检查"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_onnx", "onnx"),
        ("ONNX",),
        "proficiency",
        "ONNX 推理部署与优化",
        "完成 ONNX Runtime 部署、精度校验与性能优化，提交部署脚本、基准与对比",
        ("部署可复现", "精度与性能指标可量化", "包含至少一组优化对比"),
        12.0,
        ("ONNX Runtime", "精度校验", "推理优化"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_onnx", "onnx"),
        ("ONNX",),
        "project",
        "ONNX 部署实践",
        "完成一个 ONNX 模型部署项目，提交转换、服务、压测与验证结果",
        ("部署方案可复现", "服务可运行并通过验收", "形成指标与复盘说明"),
        24.0,
        ("模型部署", "服务压测", "上线验证"),
    ),
    LearningAsset(
        ("skill_onnx", "onnx"),
        ("ONNX",),
        "ownership",
        "独立负责 ONNX 推理链路",
        "独立负责 ONNX 推理链路从选型到交付，提交方案、基准、监控与线上证据",
        ("独立负责范围可核验", "链路可监控可回滚", "性能影响可溯源"),
        32.0,
        ("推理链路", "基准治理", "线上监控"),
    ),
    # MCP
    LearningAsset(
        ("skill_mcp", "mcp"),
        ("MCP",),
        "foundation",
        "MCP 协议与工具接入基础",
        "完成 MCP 协议、工具定义与客户端接入练习，提交可运行的工具服务示例与说明",
        ("示例可运行", "理解工具、资源与提示协议", "保留接入记录"),
        8.0,
        ("MCP 文档", "工具协议", "客户端接入"),
        ("basic", "unknown"),
    ),
    LearningAsset(
        ("skill_mcp", "mcp"),
        ("MCP",),
        "proficiency",
        "MCP 服务开发与集成",
        "完成一个 MCP 服务与多客户端集成实践，提交服务实现、鉴权、日志与验证结果",
        ("服务可运行并通过集成", "鉴权与日志完整", "记录调用与异常场景"),
        12.0,
        ("MCP 服务", "鉴权", "集成验证"),
        ("working", "proficient"),
    ),
    LearningAsset(
        ("skill_mcp", "mcp"),
        ("MCP",),
        "project",
        "MCP 工具链实践",
        "完成一个面向真实业务的 MCP 工具链，提交服务、工具、评测与运行证据",
        ("工具链可运行并通过验收", "评测指标与业务目标对应", "形成复盘与改进说明"),
        24.0,
        ("工具链", "业务接入", "效果评测"),
    ),
    LearningAsset(
        ("skill_mcp", "mcp"),
        ("MCP",),
        "ownership",
        "独立负责 MCP 服务建设",
        "独立负责 MCP 服务能力从设计到线上交付，提交架构、监控、治理与线上证据",
        ("独立负责范围可核验", "服务可监控可治理", "业务影响可溯源"),
        32.0,
        ("服务建设", "线上监控", "治理规范"),
    ),
)


_STAGE_CRITERIA = {
    "foundation": ("基础练习可复现", "覆盖核心知识点并保留练习记录", "能说明关键概念与运行结果"),
    "proficiency": ("达到目标等级的能力评估", "在任务或练习中演示通过", "产出可核验记录"),
    "project": ("交付物完整且可运行", "验收标准明确", "形成指标记录与复盘说明"),
    "ownership": ("独立负责范围可核验", "交付物可运行且可维护", "成果与影响可溯源"),
}


def _stage_assets(
    skill_ids: tuple[str, ...],
    names: tuple[str, ...],
    foundation: tuple[str, str],
    proficiency: tuple[str, str],
    project: tuple[str, str],
    ownership: tuple[str, str],
    keywords: tuple[str, ...],
) -> tuple[LearningAsset, ...]:
    """Expand one skill spec into the four standard learning stages."""
    stages = (
        ("foundation", 8.0, foundation, ("basic", "unknown")),
        ("proficiency", 12.0, proficiency, ("working", "proficient")),
        ("project", 24.0, project, ()),
        ("ownership", 32.0, ownership, ()),
    )
    return tuple(
        LearningAsset(
            skill_ids=skill_ids,
            names=names,
            stage=stage,
            title=title,
            deliverable=deliverable,
            acceptance_criteria=_STAGE_CRITERIA[stage],
            estimated_hours=hours,
            resource_keywords=keywords,
            target_levels=target_levels,
        )
        for stage, hours, (title, deliverable), target_levels in stages
    )


_EXTENDED_SKILLS = (
    # 大模型训练与推理
    (("skill_deepspeed", "deepspeed"), ("DeepSpeed",),
     ("DeepSpeed 分布式训练基础", "完成 DeepSpeed 环境与 ZeRO 基础练习，提交可运行训练配置与说明"),
     ("DeepSpeed 训练调优", "完成一个含 ZeRO 分片与通信优化的训练实践，提交配置、日志与性能对比"),
     ("DeepSpeed 分布式训练实践", "完成一次 DeepSpeed 分布式训练，提交启动配置与稳定性分析"),
     ("独立负责 DeepSpeed 训练工程", "独立负责 DeepSpeed 训练工程交付，提交架构、性能与线上证据"),
     ("ZeRO", "分布式训练", "显存优化")),
    (("skill_megatron", "megatron", "megatron-lm"), ("Megatron-LM", "Megatron"),
     ("Megatron 并行训练基础", "完成 Megatron 张量/流水线并行概念与配置练习，提交可运行的训练示例"),
     ("Megatron 并行策略调优", "完成 Megatron 并行策略与负载均衡调优，提交配置、日志与性能对比"),
     ("Megatron 大模型训练实践", "完成一次 Megatron 大模型训练，提交并行配置、吞吐与稳定性分析"),
     ("独立负责 Megatron 训练工程", "独立负责 Megatron 训练工程交付，提交方案、指标与线上证据"),
     ("张量并行", "流水线并行", "训练吞吐")),
    (("skill_peft", "peft"), ("PEFT",),
     ("PEFT 参数高效微调基础", "完成 PEFT 适配器、前缀与提示微调概念练习，提交可运行的配置示例"),
     ("PEFT 微调实践", "完成一次 PEFT 微调与评估，提交配置、数据、指标与推理示例"),
     ("PEFT 微调项目实践", "完成一个面向业务数据的 PEFT 微调项目，提交管线、评估与结果分析"),
     ("独立负责 PEFT 微调工程", "独立负责 PEFT 微调能力从数据到交付，提交工程、评估与线上验证"),
     ("适配器", "参数高效微调", "效果评估")),
    (("skill_sft", "sft"), ("SFT",),
     ("SFT 监督微调基础", "完成指令数据构建与 SFT 训练概念练习，提交数据样例与训练配置"),
     ("SFT 数据与训练实践", "完成一次 SFT 训练与评估，提交数据规范、训练日志与效果对比"),
     ("SFT 模型微调实践", "完成一个面向业务指令的 SFT 项目，提交数据管线、训练与评估报告"),
     ("独立负责 SFT 微调工程", "独立负责 SFT 数据与训练工程，提交规范、评估与线上验证"),
     ("指令数据", "监督微调", "效果评估")),
    (("skill_dpo", "dpo"), ("DPO",),
     ("DPO 偏好优化基础", "完成偏好数据与 DPO 训练概念练习，提交可运行的训练配置示例"),
     ("DPO 训练与评估", "完成一次 DPO 训练与偏好评估，提交数据、日志与指标对比"),
     ("DPO 对齐实践", "完成一个偏好对齐项目，提交数据构建、训练、评估与结果分析"),
     ("独立负责 DPO 对齐工程", "独立负责 DPO 对齐能力从数据到交付，提交工程、评估与线上验证"),
     ("偏好数据", "对齐", "效果评估")),
    (("skill_ppo", "ppo"), ("PPO",),
     ("PPO 强化学习基础", "完成 PPO 算法与训练循环概念练习，提交可运行的示例与说明"),
     ("PPO 训练实践", "完成一次 PPO 训练与评估，提交环境、奖励设计与训练日志"),
     ("PPO 强化学习实践", "完成一个面向任务的 PPO 实践，提交训练、评估与稳定性分析"),
     ("独立负责 PPO 训练工程", "独立负责 PPO 训练工程从环境到交付，提交方案、指标与线上证据"),
     ("强化学习", "奖励设计", "训练稳定性")),
    (("skill_grpo", "grpo"), ("GRPO",),
     ("GRPO 组相对策略优化基础", "完成 GRPO 组采样与相对奖励概念练习，提交可运行的配置示例"),
     ("GRPO 训练与评估", "完成一次 GRPO 训练与评估，提交采样、奖励与训练日志"),
     ("GRPO 对齐实践", "完成一个 GRPO 对齐项目，提交数据、训练、评估与结果分析"),
     ("独立负责 GRPO 训练工程", "独立负责 GRPO 训练能力从数据到交付，提交工程与线上验证"),
     ("组相对策略", "奖励模型", "对齐")),
    (("skill_rlhf", "rlhf"), ("RLHF",),
     ("RLHF 人类反馈强化学习基础", "完成奖励模型与 RLHF 管线概念练习，提交可运行的示例与说明"),
     ("RLHF 管线实践", "完成一次奖励模型训练与 RLHF 微调，提交数据、日志与评估对比"),
     ("RLHF 对齐实践", "完成一个 RLHF 对齐项目，提交数据、训练、评估与结果分析"),
     ("独立负责 RLHF 对齐工程", "独立负责 RLHF 管线从数据到交付，提交工程、评估与线上验证"),
     ("奖励模型", "人类反馈", "对齐")),
    (("skill_llama_cpp", "llama.cpp", "llama-cpp"), ("llama.cpp",),
     ("llama.cpp 本地推理基础", "完成 llama.cpp 构建、量化与本地推理练习，提交配置与运行记录"),
     ("llama.cpp 推理调优", "完成 llama.cpp 推理参数与量化调优，提交基准与对比结果"),
     ("llama.cpp 本地服务实践", "完成一个基于 llama.cpp 的本地推理服务，提交部署、压测与验证"),
     ("独立负责 llama.cpp 推理服务", "独立负责本地推理服务从建设到治理，提交方案、监控与线上证据"),
     ("本地推理", "量化", "GGUF")),
    (("skill_triton", "triton", "triton-inference-server"), ("Triton Inference Server", "Triton"),
     ("Triton 推理服务基础", "完成 Triton 模型仓、并发与动态批处理练习，提交可运行的服务配置"),
     ("Triton 服务优化", "完成 Triton 并发、批处理与性能调优，提交配置、压测与指标对比"),
     ("Triton 推理服务实践", "完成一个 Triton 推理服务部署项目，提交模型仓、监控与验证结果"),
     ("独立负责 Triton 推理平台", "独立负责 Triton 推理平台从建设到治理，提交架构、容量与线上证据"),
     ("动态批处理", "模型仓", "推理压测")),
    (("skill_openvino", "openvino"), ("OpenVINO",),
     ("OpenVINO 推理基础", "完成 OpenVINO 模型转换与推理练习，提交转换配置与运行记录"),
     ("OpenVINO 推理优化", "完成 OpenVINO 精度与性能优化，提交基准与对比结果"),
     ("OpenVINO 部署实践", "完成一个 OpenVINO 边缘部署项目，提交转换、服务与验证结果"),
     ("独立负责 OpenVINO 推理链路", "独立负责 OpenVINO 推理链路从选型到交付，提交方案与线上证据"),
     ("模型转换", "边缘推理", "性能优化")),
    (("skill_faiss", "faiss"), ("FAISS",),
     ("FAISS 向量检索基础", "完成 FAISS 索引构建与检索练习，提交可运行的示例与说明"),
     ("FAISS 索引调优", "完成 FAISS 索引选型与检索调优，提交基准与对比结果"),
     ("FAISS 检索系统实践", "完成一个基于 FAISS 的检索系统，提交索引、服务与效果评估"),
     ("独立负责 FAISS 检索服务", "独立负责向量检索服务从建设到治理，提交架构、监控与线上证据"),
     ("向量索引", "召回评估", "检索服务")),
    (("skill_qdrant", "qdrant"), ("Qdrant",),
     ("Qdrant 向量数据库基础", "完成 Qdrant 集合、索引与检索练习，提交配置与运行记录"),
     ("Qdrant 检索调优", "完成 Qdrant 索引与检索参数调优，提交基准与对比结果"),
     ("Qdrant 检索系统实践", "完成一个基于 Qdrant 的检索系统，提交数据、索引与效果评估"),
     ("独立负责 Qdrant 检索平台", "独立负责向量检索平台从建设到治理，提交架构与线上证据"),
     ("向量检索", "索引调优", "效果评估")),
    (("skill_weaviate", "weaviate"), ("Weaviate",),
     ("Weaviate 向量检索基础", "完成 Weaviate 类与对象管理及检索练习，提交配置与运行记录"),
     ("Weaviate 检索调优", "完成 Weaviate 索引与混合检索调优，提交基准与对比结果"),
     ("Weaviate 检索系统实践", "完成一个基于 Weaviate 的检索系统，提交数据、服务与效果评估"),
     ("独立负责 Weaviate 检索平台", "独立负责向量检索平台从建设到治理，提交架构与线上证据"),
     ("混合检索", "向量数据库", "效果评估")),
    (("skill_chroma", "chroma"), ("Chroma",),
     ("Chroma 向量库基础", "完成 Chroma 集合与检索练习，提交可运行的示例与说明"),
     ("Chroma 检索调优", "完成 Chroma 索引与检索参数调优，提交基准与对比结果"),
     ("Chroma 检索应用实践", "完成一个基于 Chroma 的检索应用，提交数据、服务与效果评估"),
     ("独立负责 Chroma 检索服务", "独立负责 Chroma 检索服务从建设到治理，提交架构与线上证据"),
     ("向量检索", "嵌入", "应用集成")),
    (("skill_langchain", "langchain"), ("LangChain",),
     ("LangChain 框架基础", "完成 LangChain 模型、提示与链式调用练习，提交可运行示例"),
     ("LangChain 应用开发", "完成一个含检索与工具调用的 LangChain 应用，提交代码与运行记录"),
     ("LangChain 应用实践", "完成一个面向真实任务的 LangChain 应用，提交设计、评测与运行证据"),
     ("独立负责 LangChain 应用平台", "独立负责 LangChain 应用能力交付，提交架构与线上证据"),
     ("链式调用", "工具调用", "应用集成")),
    (("skill_llamaindex", "llamaindex", "llama-index"), ("LlamaIndex",),
     ("LlamaIndex 数据框架基础", "完成 LlamaIndex 文档加载、索引与查询练习，提交可运行示例"),
     ("LlamaIndex 检索增强开发", "完成一个含索引与查询引擎的 LlamaIndex 应用，提交代码与运行记录"),
     ("LlamaIndex 知识库实践", "完成一个知识库 LlamaIndex 应用，提交索引、评测与结果分析"),
     ("独立负责知识库检索平台", "独立负责知识库检索能力从建设到治理，提交架构与线上证据"),
     ("文档索引", "查询引擎", "知识库")),
    (("skill_huggingface", "huggingface", "transformers-hf"), ("Hugging Face",),
     ("Hugging Face 生态基础", "完成模型库、Datasets 与 Tokenizer 练习，提交可运行示例与说明"),
     ("Hugging Face 训练与推理", "完成一次基于 Hugging Face 的训练与推理实践，提交脚本与评估结果"),
     ("Hugging Face 应用实践", "完成一个 Hugging Face 应用项目，提交数据、训练与部署说明"),
     ("独立负责 Hugging Face 工程", "独立负责 Hugging Face 模型工程交付，提交工程与线上证据"),
     ("Model Hub", "Datasets", "Tokenizer")),
    (("skill_lightning", "pytorch-lightning", "lightning"), ("PyTorch Lightning",),
     ("PyTorch Lightning 基础", "完成 Lightning 模块、训练器与回调练习，提交可运行的训练示例"),
     ("Lightning 训练工程", "完成一个 Lightning 训练工程，提交训练循环、日志与评估结果"),
     ("Lightning 训练实践", "完成一个面向任务的 Lightning 训练项目，提交配置、指标与结果分析"),
     ("独立负责 Lightning 训练工程", "独立负责 Lightning 训练工程从环境到交付，提交工程与线上证据"),
     ("Trainer", "回调", "训练工程")),
    (("skill_tensorflow", "tensorflow", "tf"), ("TensorFlow",),
     ("TensorFlow 基础", "完成 TensorFlow 张量、Keras 模型与训练练习，提交可运行示例"),
     ("TensorFlow 模型开发", "完成一个 TensorFlow 模型训练与评估，提交脚本、日志与指标"),
     ("TensorFlow 应用实践", "完成一个面向业务的 TensorFlow 项目，提交数据、训练与部署说明"),
     ("独立负责 TensorFlow 模型工程", "独立负责 TensorFlow 模型工程交付，提交工程与线上证据"),
     ("Keras", "模型训练", "部署")),
    (("skill_jax", "jax"), ("JAX",),
     ("JAX 基础", "完成 JAX 数组、jit 与 grad 练习，提交可运行的示例与说明"),
     ("JAX 训练实践", "完成一个 JAX 模型训练与评估，提交训练循环与指标"),
     ("JAX 应用实践", "完成一个面向任务的 JAX 项目，提交训练、评估与结果分析"),
     ("独立负责 JAX 模型工程", "独立负责 JAX 模型工程从环境到交付，提交工程与线上证据"),
     ("jit", "自动微分", "训练")),
    (("skill_scikit_learn", "scikit-learn", "sklearn"), ("scikit-learn",),
     ("scikit-learn 机器学习基础", "完成数据预处理、模型训练与评估练习，提交可运行的示例"),
     ("scikit-learn 建模与调优", "完成一个含交叉验证与超参搜索的建模实践，提交指标与对比"),
     ("scikit-learn 建模实践", "完成一个面向业务数据的建模项目，提交特征、模型与评估报告"),
     ("独立负责机器学习建模", "独立负责建模能力从数据到交付，提交模型、评估与线上验证"),
     ("交叉验证", "超参搜索", "模型评估")),
    (("skill_xgboost", "xgboost"), ("XGBoost",),
     ("XGBoost 基础", "完成 XGBoost 训练、特征重要性与评估练习，提交可运行示例"),
     ("XGBoost 建模调优", "完成一个 XGBoost 建模与调优实践，提交参数、指标与对比"),
     ("XGBoost 建模实践", "完成一个面向业务数据的 XGBoost 项目，提交模型、评估与结果分析"),
     ("独立负责 XGBoost 模型工程", "独立负责 XGBoost 建模能力从数据到交付，提交工程与线上验证"),
     ("梯度提升", "特征重要性", "模型评估")),
    (("skill_lightgbm", "lightgbm"), ("LightGBM",),
     ("LightGBM 基础", "完成 LightGBM 训练与评估练习，提交可运行的示例与说明"),
     ("LightGBM 建模调优", "完成一个 LightGBM 建模与调优实践，提交参数与指标对比"),
     ("LightGBM 建模实践", "完成一个面向业务数据的 LightGBM 项目，提交模型与评估报告"),
     ("独立负责 LightGBM 模型工程", "独立负责 LightGBM 建模能力从数据到交付，提交工程与线上验证"),
     ("梯度提升", "直方图算法", "模型评估")),
    (("skill_whisper", "whisper"), ("Whisper",),
     ("Whisper 语音识别基础", "完成 Whisper 模型加载与音频转写练习，提交可运行示例与说明"),
     ("Whisper 微调与评测", "完成一次 Whisper 微调与识别评测，提交数据、指标与结果"),
     ("Whisper 语音应用实践", "完成一个面向业务的语音识别应用，提交数据、服务与效果评估"),
     ("独立负责语音识别能力", "独立负责语音识别能力从数据到交付，提交工程与线上验证"),
     ("语音识别", "转写", "微调")),
    (("skill_clip", "clip"), ("CLIP",),
     ("CLIP 多模态基础", "完成 CLIP 图文表征与检索练习，提交可运行示例与说明"),
     ("CLIP 微调与评估", "完成一次 CLIP 微调与图文检索评估，提交数据、指标与结果"),
     ("CLIP 多模态应用实践", "完成一个面向业务的多模态应用，提交数据、服务与效果评估"),
     ("独立负责多模态能力", "独立负责多模态表征能力从数据到交付，提交工程与线上验证"),
     ("图文检索", "多模态", "表征学习")),
    (("skill_stable_diffusion", "stable-diffusion", "stable_diffusion"), ("Stable Diffusion",),
     ("Stable Diffusion 基础", "完成模型加载、文生图与参数练习，提交可运行示例与结果"),
     ("Stable Diffusion 生成调优", "完成提示词、采样与 LoRA 生成调优，提交效果与参数对比"),
     ("Stable Diffusion 应用实践", "完成一个面向业务的生成应用，提交数据、服务与效果评估"),
     ("独立负责图像生成能力", "独立负责图像生成能力从设计到交付，提交工程与线上验证"),
     ("文生图", "采样器", "LoRA 生成")),
    (("skill_controlnet", "controlnet"), ("ControlNet",),
     ("ControlNet 可控生成基础", "完成 ControlNet 条件控制与模型加载练习，提交可运行示例"),
     ("ControlNet 生成调优", "完成条件强度与多条件控制调优，提交效果与参数对比"),
     ("ControlNet 应用实践", "完成一个面向业务的可控生成应用，提交数据、服务与效果评估"),
     ("独立负责可控生成能力", "独立负责可控生成能力从设计到交付，提交工程与线上验证"),
     ("条件生成", "姿态控制", "边缘控制")),
    (("skill_reranker", "reranker", "cross-encoder"), ("Reranker", "Cross-Encoder"),
     ("Reranker 重排基础", "完成交叉编码器与重排概念练习，提交可运行的检索重排示例"),
     ("Reranker 重排调优", "完成重排模型训练与效果调优，提交数据、指标与对比"),
     ("Reranker 检索优化实践", "完成一个检索重排优化项目，提交召回-重排-评估报告"),
     ("独立负责重排能力", "独立负责检索重排能力从数据到交付，提交工程与线上验证"),
     ("重排", "交叉编码器", "检索优化")),
    (("skill_ragas", "ragas"), ("RAGAS",),
     ("RAGAS 评测基础", "完成 RAG 评测指标与 RAGAS 调用练习，提交可运行的评测示例"),
     ("RAGAS 评测实践", "完成一套 RAG 评测集与指标分析，提交评测脚本与结果报告"),
     ("RAG 质量评测实践", "完成一个 RAG 系统质量评测项目，提交指标、问题定位与改进建议"),
     ("独立负责 RAG 评测治理", "独立负责 RAG 效果评测与治理，提交规范、报告与线上证据"),
     ("评测指标", "忠实度", "答案相关性")),
    (("skill_graphrag", "graphrag"), ("GraphRAG",),
     ("GraphRAG 基础", "完成知识图谱构建与 GraphRAG 查询概念练习，提交可运行示例与说明"),
     ("GraphRAG 检索实践", "完成图谱增强检索与问答实践，提交构建、查询与评估结果"),
     ("GraphRAG 应用实践", "完成一个面向业务知识的 GraphRAG 应用，提交图谱、评测与结果分析"),
     ("独立负责 GraphRAG 能力", "独立负责 GraphRAG 能力从建设到治理，提交架构与线上证据"),
     ("知识图谱", "图检索", "问答")),
    (("skill_ollama", "ollama"), ("Ollama",),
     ("Ollama 本地模型基础", "完成 Ollama 模型拉取、运行与 API 调用练习，提交配置与运行记录"),
     ("Ollama 服务实践", "完成 Ollama 服务部署与并发调用，提交配置、压测与结果"),
     ("Ollama 本地应用实践", "完成一个基于 Ollama 的本地应用，提交服务、集成与验证结果"),
     ("独立负责本地模型服务", "独立负责本地模型服务从建设到治理，提交方案、监控与线上证据"),
     ("本地模型", "API 服务", "模型管理")),
)

_LEARNING_ASSETS = (
    *_LEARNING_ASSETS,
    *tuple(
        asset
        for spec in _EXTENDED_SKILLS
        for asset in _stage_assets(*spec)
    ),
)


_EXTENDED_SKILLS_2 = (
    # 数据与算法工程
    (("skill_pandas", "pandas"), ("Pandas",),
     ("Pandas 数据处理基础", "完成 DataFrame 读写、清洗与聚合练习，提交可运行代码与说明"),
     ("Pandas 数据工程", "完成一个含合并、分组与窗口计算的数据处理实践，提交代码与结果"),
     ("Pandas 数据处理实践", "完成一个面向业务数据的数据处理项目，提交管线与质量报告"),
     ("独立负责 Pandas 数据管线", "独立负责数据处理管线从设计到交付，提交规范与验证结果"),
     ("DataFrame", "数据清洗", "聚合分析")),
    (("skill_numpy", "numpy"), ("NumPy",),
     ("NumPy 数值计算基础", "完成数组、广播与向量化计算练习，提交可运行代码与说明"),
     ("NumPy 数值优化", "完成一个含性能优化的数值计算实践，提交代码与基准对比"),
     ("NumPy 计算实践", "完成一个面向业务的计算项目，提交算法、验证与结果分析"),
     ("独立负责数值计算模块", "独立负责数值计算模块从设计到交付，提交工程与验证结果"),
     ("数组运算", "广播", "向量化")),
    (("skill_polars", "polars"), ("Polars",),
     ("Polars 数据处理基础", "完成 Polars 表达式与惰性计算练习，提交可运行代码与说明"),
     ("Polars 数据管线", "完成一个 Polars 数据处理实践，提交代码、性能与结果"),
     ("Polars 数据处理实践", "完成一个面向业务数据的 Polars 项目，提交管线与质量报告"),
     ("独立负责 Polars 数据管线", "独立负责基于 Polars 的数据管线从设计到交付，提交规范与验证"),
     ("表达式", "惰性计算", "性能")),
    (("skill_duckdb", "duckdb"), ("DuckDB",),
     ("DuckDB 分析基础", "完成 DuckDB 查询、Parquet 读取与窗口函数练习，提交可运行示例"),
     ("DuckDB 分析优化", "完成一个分析查询优化实践，提交查询计划与性能对比"),
     ("DuckDB 分析实践", "完成一个面向业务数据的分析项目，提交查询、验证与结果"),
     ("独立负责分析数据服务", "独立负责分析数据服务从建设到治理，提交方案与线上证据"),
     ("OLAP", "Parquet", "分析查询")),
    (("skill_sqlite", "sqlite"), ("SQLite",),
     ("SQLite 数据库基础", "完成 SQLite 建表、查询与事务练习，提交可运行示例与说明"),
     ("SQLite 应用集成", "完成一个 SQLite 应用集成实践，提交数据模型与查询结果"),
     ("SQLite 数据应用实践", "完成一个面向业务的 SQLite 应用，提交设计、实现与验证"),
     ("独立负责数据存储模块", "独立负责本地数据存储模块从设计到交付，提交工程与验证"),
     ("SQL", "事务", "嵌入式数据库")),
    (("skill_postgresql", "postgresql", "postgres"), ("PostgreSQL",),
     ("PostgreSQL 基础", "完成 PostgreSQL 建表、查询、索引与事务练习，提交 SQL 脚本与结果"),
     ("PostgreSQL 优化", "完成执行计划、索引与并发控制优化，提交优化前后对比"),
     ("PostgreSQL 应用实践", "完成一个面向业务的 PostgreSQL 项目，提交设计、压测与结果"),
     ("独立负责 PostgreSQL 数据架构", "独立负责 PostgreSQL 架构治理，提交方案、监控与线上证据"),
     ("SQL", "索引优化", "事务")),
    (("skill_mongodb", "mongodb", "mongo"), ("MongoDB",),
     ("MongoDB 基础", "完成 MongoDB 集合、文档与查询练习，提交可运行示例与说明"),
     ("MongoDB 建模与调优", "完成数据建模与索引调优实践，提交模型、指标与对比"),
     ("MongoDB 应用实践", "完成一个面向业务的 MongoDB 应用，提交设计、实现与验证"),
     ("独立负责 MongoDB 数据服务", "独立负责 MongoDB 数据服务从建设到治理，提交架构与线上证据"),
     ("文档模型", "索引", "副本集")),
    (("skill_elasticsearch", "elasticsearch", "es"), ("Elasticsearch",),
     ("Elasticsearch 基础", "完成索引、映射与查询练习，提交可运行示例与说明"),
     ("Elasticsearch 检索优化", "完成分词、相关性评分与性能调优，提交指标与对比"),
     ("Elasticsearch 检索应用实践", "完成一个面向业务的检索应用，提交索引、服务与效果评估"),
     ("独立负责 Elasticsearch 平台", "独立负责 Elasticsearch 平台从建设到治理，提交架构与线上证据"),
     ("全文检索", "倒排索引", "相关性")),
    (("skill_opensearch", "opensearch"), ("OpenSearch",),
     ("OpenSearch 检索基础", "完成 OpenSearch 索引与查询练习，提交可运行示例与说明"),
     ("OpenSearch 检索调优", "完成分词与性能调优实践，提交指标与对比"),
     ("OpenSearch 检索应用实践", "完成一个面向业务的检索应用，提交索引、服务与效果评估"),
     ("独立负责 OpenSearch 平台", "独立负责 OpenSearch 平台从建设到治理，提交架构与线上证据"),
     ("全文检索", "向量检索", "性能调优")),
    (("skill_clickhouse", "clickhouse", "ch"), ("ClickHouse",),
     ("ClickHouse 基础", "完成 ClickHouse 建表、导入与查询练习，提交可运行示例与说明"),
     ("ClickHouse 查询优化", "完成分区、物化视图与查询调优，提交指标与对比"),
     ("ClickHouse 分析实践", "完成一个面向业务的分析应用，提交表设计、查询与验证"),
     ("独立负责 ClickHouse 数据平台", "独立负责 ClickHouse 分析平台治理，提交架构与线上证据"),
     ("列式存储", "物化视图", "分析查询")),
    (("skill_kafka", "kafka"), ("Kafka",),
     ("Kafka 消息队列基础", "完成 Kafka 主题、生产者与消费者练习，提交可运行示例与说明"),
     ("Kafka 流处理", "完成分区、消费组与幂等配置实践，提交指标与结果"),
     ("Kafka 消息平台实践", "完成一个面向业务的消息平台项目，提交架构、监控与验证"),
     ("独立负责 Kafka 消息平台", "独立负责 Kafka 消息平台从建设到治理，提交架构、容量与线上证据"),
     ("Topic", "消费组", "流处理")),
    (("skill_rabbitmq", "rabbitmq"), ("RabbitMQ",),
     ("RabbitMQ 基础", "完成交换机、队列与消息确认练习，提交可运行示例与说明"),
     ("RabbitMQ 可靠性实践", "完成消息可靠投递与消费实践，提交配置、日志与结果"),
     ("RabbitMQ 消息服务实践", "完成一个面向业务的消息服务，提交架构、监控与验证"),
     ("独立负责消息中间件", "独立负责消息中间件从建设到治理，提交架构与线上证据"),
     ("交换机", "消息确认", "可靠性")),
    (("skill_airflow", "airflow"), ("Airflow",),
     ("Airflow 调度基础", "完成 DAG、任务依赖与调度器练习，提交可运行示例与说明"),
     ("Airflow 数据管线", "完成一个多任务数据管线实践，提交 DAG、日志与结果"),
     ("Airflow 调度平台实践", "完成一个面向业务的数据调度平台，提交 DAG、监控与验证"),
     ("独立负责数据调度平台", "独立负责数据调度平台从建设到治理，提交架构、监控与线上证据"),
     ("DAG", "任务调度", "数据管线")),
    (("skill_dbt", "dbt"), ("dbt",),
     ("dbt 数据建模基础", "完成 dbt 项目、模型与测试练习，提交可运行示例与说明"),
     ("dbt 数据工程", "完成一个含转换与测试的 dbt 实践，提交模型、文档与结果"),
     ("dbt 数据管线实践", "完成一个面向业务的数据建模项目，提交模型、测试与验证"),
     ("独立负责 dbt 数据工程", "独立负责 dbt 数据工程从建模到治理，提交规范与线上证据"),
     ("数据建模", "模型测试", "数据文档")),
    (("skill_trino", "trino", "presto"), ("Trino", "Presto"),
     ("Trino 查询基础", "完成 Trino 连接器与 SQL 查询练习，提交可运行示例与说明"),
     ("Trino 查询优化", "完成跨源查询与执行调优实践，提交指标与对比"),
     ("Trino 数据平台实践", "完成一个跨源分析平台项目，提交架构、查询与验证"),
     ("独立负责 Trino 查询平台", "独立负责 Trino 查询平台从建设到治理，提交架构与线上证据"),
     ("跨源查询", "连接器", "查询优化")),
    (("skill_iceberg", "iceberg"), ("Apache Iceberg", "Iceberg"),
     ("Iceberg 表格式基础", "完成 Iceberg 表创建、快照与时间旅行练习，提交配置与说明"),
     ("Iceberg 数据湖实践", "完成增量读写与表维护实践，提交操作、指标与结果"),
     ("Iceberg 数据湖项目实践", "完成一个面向业务的数据湖项目，提交表设计、验证与结果"),
     ("独立负责数据湖表治理", "独立负责 Iceberg 表治理从建设到交付，提交规范与线上证据"),
     ("快照", "时间旅行", "数据湖")),
    (("skill_delta_lake", "delta-lake", "delta_lake"), ("Delta Lake",),
     ("Delta Lake 基础", "完成 Delta 表、事务日志与时间旅行练习，提交配置与说明"),
     ("Delta Lake 数据工程", "完成增量处理与表优化实践，提交操作、指标与结果"),
     ("Delta Lake 数据湖实践", "完成一个面向业务的数据湖项目，提交表设计、验证与结果"),
     ("独立负责 Delta 表治理", "独立负责 Delta 表治理从建设到交付，提交规范与线上证据"),
     ("ACID", "时间旅行", "增量处理")),
    (("skill_hadoop", "hadoop"), ("Hadoop",),
     ("Hadoop 基础", "完成 HDFS 与 MapReduce 概念练习，提交配置与运行记录"),
     ("Hadoop 数据处理", "完成一个 MapReduce 或 YARN 作业实践，提交作业、日志与结果"),
     ("Hadoop 平台实践", "完成一个面向业务的数据处理平台项目，提交架构、监控与验证"),
     ("独立负责 Hadoop 集群", "独立负责 Hadoop 集群从建设到治理，提交架构、容量与线上证据"),
     ("HDFS", "MapReduce", "YARN")),
    (("skill_hdfs", "hdfs"), ("HDFS",),
     ("HDFS 基础", "完成 HDFS 命令、副本与块概念练习，提交操作记录与说明"),
     ("HDFS 运维实践", "完成数据读写、配额与故障处理实践，提交操作与结果"),
     ("HDFS 存储实践", "完成一个面向业务的分布式存储项目，提交架构、监控与验证"),
     ("独立负责 HDFS 存储治理", "独立负责 HDFS 存储从建设到治理，提交架构、容量与线上证据"),
     ("分布式存储", "副本", "数据块")),
    (("skill_minio", "minio", "s3"), ("MinIO", "S3"),
     ("MinIO 对象存储基础", "完成桶、对象与访问策略练习，提交可运行示例与说明"),
     ("MinIO 服务实践", "完成对象存储服务与客户端集成实践，提交配置、指标与结果"),
     ("MinIO 存储平台实践", "完成一个面向业务的对象存储项目，提交架构、监控与验证"),
     ("独立负责对象存储平台", "独立负责对象存储平台从建设到治理，提交架构、容量与线上证据"),
     ("对象存储", "S3 协议", "生命周期")),
    (("skill_streamlit", "streamlit"), ("Streamlit",),
     ("Streamlit 应用基础", "完成 Streamlit 组件与数据展示练习，提交可运行应用"),
     ("Streamlit 数据应用", "完成一个含交互与状态管理的数据应用，提交代码与运行说明"),
     ("Streamlit 应用实践", "完成一个面向业务的数据应用，提交界面、逻辑与验证"),
     ("独立负责数据应用交付", "独立负责数据应用从设计到交付，提交工程与验证结果"),
     ("数据应用", "交互组件", "可视化")),
    (("skill_gradio", "gradio"), ("Gradio",),
     ("Gradio 应用基础", "完成 Gradio 组件与模型演示练习，提交可运行应用"),
     ("Gradio 模型应用", "完成一个含输入输出与队列的模型应用，提交代码与运行说明"),
     ("Gradio 应用实践", "完成一个面向业务的模型演示应用，提交界面、逻辑与验证"),
     ("独立负责模型演示应用", "独立负责模型演示应用从设计到交付，提交工程与验证结果"),
     ("模型演示", "交互组件", "部署")),
    # DevOps 与可观测
    (("skill_helm", "helm"), ("Helm",),
     ("Helm 基础", "完成 Chart 结构、模板与发布练习，提交可运行 Chart 与说明"),
     ("Helm 应用部署", "完成一个应用的 Helm 打包与升级实践，提交 Chart、参数与结果"),
     ("Helm 部署实践", "完成一个面向业务的 Helm 部署项目，提交 Chart、验证与结果"),
     ("独立负责 Helm 发布治理", "独立负责 Helm 发布治理从规范到交付，提交流程与线上证据"),
     ("Chart", "模板", "发布管理")),
    (("skill_terraform", "terraform"), ("Terraform",),
     ("Terraform 基础", "完成资源定义、状态与计划练习，提交可运行配置与说明"),
     ("Terraform 基础设施", "完成一个环境的 Terraform 管理实践，提交模块、状态与结果"),
     ("Terraform 平台实践", "完成一个面向业务的基础设施项目，提交模块、验证与结果"),
     ("独立负责 IaC 治理", "独立负责基础设施即代码治理从规范到交付，提交流程与线上证据"),
     ("IaC", "状态管理", "资源编排")),
    (("skill_ansible", "ansible"), ("Ansible",),
     ("Ansible 基础", "完成清单、模块与 Playbook 练习，提交可运行配置与说明"),
     ("Ansible 自动化", "完成一个自动化配置实践，提交 Playbook、角色与结果"),
     ("Ansible 运维实践", "完成一个面向业务的运维自动化项目，提交配置、验证与结果"),
     ("独立负责运维自动化", "独立负责运维自动化从规范到交付，提交流程与线上证据"),
     ("Playbook", "角色", "配置管理")),
    (("skill_prometheus", "prometheus"), ("Prometheus",),
     ("Prometheus 监控基础", "完成指标采集、查询与告警规则练习，提交配置与说明"),
     ("Prometheus 监控实践", "完成一个服务的监控与告警配置，提交指标、规则与结果"),
     ("Prometheus 监控平台实践", "完成一个面向业务的监控平台，提交架构、告警与验证"),
     ("独立负责监控平台", "独立负责监控平台从建设到治理，提交架构与线上证据"),
     ("指标采集", "PromQL", "告警")),
    (("skill_grafana", "grafana"), ("Grafana",),
     ("Grafana 可视化基础", "完成数据源、面板与仪表盘练习，提交可运行示例与说明"),
     ("Grafana 监控面板", "完成一个服务的监控面板实践，提交面板、指标与结果"),
     ("Grafana 平台实践", "完成一个面向业务的观测平台，提交仪表盘、告警与验证"),
     ("独立负责观测平台", "独立负责观测平台从建设到治理，提交架构与线上证据"),
     ("仪表盘", "数据源", "告警")),
    (("skill_opentelemetry", "opentelemetry", "otel"), ("OpenTelemetry",),
     ("OpenTelemetry 基础", "完成 Trace、Metric 与 Log 采集练习，提交配置与说明"),
     ("OpenTelemetry 接入", "完成一个服务的埋点与导出实践，提交采集、链路与结果"),
     ("OpenTelemetry 可观测实践", "完成一个面向业务的可观测项目，提交架构、数据与验证"),
     ("独立负责可观测链路", "独立负责可观测链路从建设到治理，提交架构与线上证据"),
     ("Trace", "Metric", "采集器")),
    (("skill_argocd", "argocd"), ("Argo CD", "ArgoCD"),
     ("Argo CD 基础", "完成应用、项目与同步策略练习，提交可运行配置与说明"),
     ("Argo CD 发布实践", "完成一个应用的 GitOps 发布实践，提交仓库、同步与结果"),
     ("Argo CD 平台实践", "完成一个面向业务的 GitOps 平台，提交架构、权限与验证"),
     ("独立负责 GitOps 治理", "独立负责 GitOps 发布治理从规范到交付，提交流程与线上证据"),
     ("GitOps", "应用同步", "发布管理")),
    (("skill_github_actions", "github-actions", "github_actions"), ("GitHub Actions",),
     ("GitHub Actions 基础", "完成工作流、触发器与 job 练习，提交可运行配置与说明"),
     ("GitHub Actions CI", "完成一个 CI 流水线实践，提交工作流、缓存与结果"),
     ("GitHub Actions 工程实践", "完成一个面向业务的 CI/CD 项目，提交流水线、验证与结果"),
     ("独立负责 CI/CD 治理", "独立负责 CI/CD 流水线治理从规范到交付，提交流程与线上证据"),
     ("工作流", "CI/CD", "自动化")),
    (("skill_nginx", "nginx"), ("Nginx",),
     ("Nginx 基础", "完成静态服务、反向代理与负载均衡练习，提交配置与说明"),
     ("Nginx 服务优化", "完成缓存、限流与 TLS 配置实践，提交配置、压测与结果"),
     ("Nginx 网关实践", "完成一个面向业务的服务网关项目，提交架构、监控与验证"),
     ("独立负责网关治理", "独立负责网关能力从建设到治理，提交架构与线上证据"),
     ("反向代理", "负载均衡", "TLS")),
    (("skill_envoy", "envoy"), ("Envoy",),
     ("Envoy 基础", "完成监听器、路由与集群练习，提交可运行配置与说明"),
     ("Envoy 代理实践", "完成一个服务的代理与流量控制实践，提交配置、指标与结果"),
     ("Envoy 网关实践", "完成一个面向业务的服务网格网关项目，提交架构、监控与验证"),
     ("独立负责服务网格治理", "独立负责服务网格能力从建设到治理，提交架构与线上证据"),
     ("服务网格", "流量控制", "可观测")),
    (("skill_istio", "istio"), ("Istio",),
     ("Istio 基础", "完成 Sidecar、VirtualService 与流量策略练习，提交配置与说明"),
     ("Istio 流量治理", "完成灰度、熔断与可观测实践，提交配置、指标与结果"),
     ("Istio 服务网格实践", "完成一个面向业务的服务网格项目，提交架构、策略与验证"),
     ("独立负责服务网格平台", "独立负责服务网格平台从建设到治理，提交架构与线上证据"),
     ("Sidecar", "灰度发布", "流量治理")),
    # 后端与语言
    (("skill_go", "go", "golang"), ("Go",),
     ("Go 基础", "完成 Go 语法、并发与标准库练习，提交可运行示例与说明"),
     ("Go 服务开发", "完成一个 Go HTTP 服务与测试实践，提交代码、测试与结果"),
     ("Go 后端实践", "完成一个面向业务的后端服务，提交设计、实现与验证"),
     ("独立负责 Go 服务交付", "独立负责 Go 服务从设计到交付，提交工程与线上证据"),
     ("并发", "HTTP 服务", "单元测试")),
    (("skill_rust", "rust"), ("Rust",),
     ("Rust 基础", "完成所有权、借用与模块练习，提交可运行示例与说明"),
     ("Rust 工程实践", "完成一个 Rust 命令行或服务实践，提交代码、测试与结果"),
     ("Rust 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Rust 服务交付", "独立负责 Rust 服务从设计到交付，提交工程与线上证据"),
     ("所有权", "并发安全", "Cargo")),
    (("skill_java", "java"), ("Java",),
     ("Java 基础", "完成 Java 语法、集合与异常练习，提交可运行示例与说明"),
     ("Java 服务开发", "完成一个 Java 服务与测试实践，提交代码、测试与结果"),
     ("Java 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Java 服务交付", "独立负责 Java 服务从设计到交付，提交工程与线上证据"),
     ("Spring", "集合框架", "单元测试")),
    (("skill_typescript", "typescript", "ts"), ("TypeScript",),
     ("TypeScript 基础", "完成类型、接口与泛型练习，提交可运行示例与说明"),
     ("TypeScript 工程实践", "完成一个 TypeScript 模块与测试实践，提交代码、类型与结果"),
     ("TypeScript 应用实践", "完成一个面向业务的前端或服务项目，提交设计、实现与验证"),
     ("独立负责 TypeScript 工程", "独立负责 TypeScript 工程从设计到交付，提交工程与线上证据"),
     ("类型系统", "泛型", "模块化")),
    (("skill_nodejs", "nodejs", "node"), ("Node.js",),
     ("Node.js 基础", "完成事件循环、模块与异步练习，提交可运行示例与说明"),
     ("Node.js 服务开发", "完成一个 Node.js 服务与测试实践，提交代码、测试与结果"),
     ("Node.js 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Node.js 服务交付", "独立负责 Node.js 服务从设计到交付，提交工程与线上证据"),
     ("异步编程", "Express", "单元测试")),
    (("skill_react", "react", "reactjs"), ("React",),
     ("React 基础", "完成组件、状态与事件练习，提交可运行示例与说明"),
     ("React 应用开发", "完成一个含路由与状态管理的应用实践，提交代码、测试与结果"),
     ("React 应用实践", "完成一个面向业务的前端项目，提交设计、实现与验证"),
     ("独立负责前端工程", "独立负责前端工程从设计到交付，提交工程与线上证据"),
     ("组件", "状态管理", "前端工程")),
    (("skill_spring_boot", "spring-boot", "springboot"), ("Spring Boot",),
     ("Spring Boot 基础", "完成依赖注入、Web 与数据访问练习，提交可运行示例与说明"),
     ("Spring Boot 服务开发", "完成一个 Spring Boot 服务与测试实践，提交代码、测试与结果"),
     ("Spring Boot 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Spring Boot 服务交付", "独立负责 Spring Boot 服务从设计到交付，提交工程与线上证据"),
     ("依赖注入", "REST API", "数据访问")),
    (("skill_django", "django"), ("Django",),
     ("Django 基础", "完成模型、视图与模板练习，提交可运行示例与说明"),
     ("Django 服务开发", "完成一个 Django 服务与测试实践，提交代码、测试与结果"),
     ("Django 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Django 服务交付", "独立负责 Django 服务从设计到交付，提交工程与线上证据"),
     ("ORM", "Django REST", "单元测试")),
    (("skill_flask", "flask"), ("Flask",),
     ("Flask 基础", "完成路由、请求与模板练习，提交可运行示例与说明"),
     ("Flask 服务开发", "完成一个 Flask 服务与测试实践，提交代码、测试与结果"),
     ("Flask 后端实践", "完成一个面向业务的后端项目，提交设计、实现与验证"),
     ("独立负责 Flask 服务交付", "独立负责 Flask 服务从设计到交付，提交工程与线上证据"),
     ("REST API", "蓝图", "单元测试")),
    (("skill_grpc", "grpc"), ("gRPC",),
     ("gRPC 基础", "完成 Proto 定义、服务与客户端练习，提交可运行示例与说明"),
     ("gRPC 服务开发", "完成一个 gRPC 服务与流式调用实践，提交代码、测试与结果"),
     ("gRPC 后端实践", "完成一个面向业务的 RPC 服务项目，提交设计、实现与验证"),
     ("独立负责 RPC 服务交付", "独立负责 RPC 服务从设计到交付，提交工程与线上证据"),
     ("ProtoBuf", "流式调用", "服务通信")),
    (("skill_graphql", "graphql"), ("GraphQL",),
     ("GraphQL 基础", "完成 Schema、查询与变更练习，提交可运行示例与说明"),
     ("GraphQL 服务开发", "完成一个 GraphQL 服务与解析器实践，提交代码、测试与结果"),
     ("GraphQL 后端实践", "完成一个面向业务的 GraphQL 项目，提交设计、实现与验证"),
     ("独立负责 GraphQL 服务交付", "独立负责 GraphQL 服务从设计到交付，提交工程与线上证据"),
     ("Schema", "解析器", "查询优化")),
    (("skill_websocket", "websocket"), ("WebSocket",),
     ("WebSocket 基础", "完成握手、消息与连接管理练习，提交可运行示例与说明"),
     ("WebSocket 服务开发", "完成一个实时消息服务实践，提交代码、测试与结果"),
     ("WebSocket 实时应用实践", "完成一个面向业务的实时应用，提交设计、实现与验证"),
     ("独立负责实时通信服务", "独立负责实时通信服务从设计到交付，提交工程与线上证据"),
     ("实时通信", "连接管理", "消息推送")),
    (("skill_bash", "bash", "shell"), ("Bash",),
     ("Bash 基础", "完成变量、条件与循环脚本练习，提交可运行脚本与说明"),
     ("Bash 自动化", "完成一个含参数与错误处理的自动化脚本实践，提交脚本与结果"),
     ("Bash 运维实践", "完成一个面向业务的脚本自动化项目，提交脚本、验证与结果"),
     ("独立负责脚本自动化", "独立负责脚本自动化从规范到交付，提交工程与验证结果"),
     ("Shell 脚本", "自动化", "运维")),
    (("skill_c", "c", "c语言"), ("C 语言", "C"),
     ("C 语言基础语法与内存模型", "完成 C 语言语法、指针、内存管理与基础数据结构"
      "练习，提交可运行代码与说明"),
     ("C 语言工程化开发", "完成一个含模块划分、编译管理与单元测试的 C 工程，"
      "提交可运行项目与测试结果"),
     ("C 语言系统实践", "完成一个面向真实任务的 C 项目，提交源码、构建说明、测试与结果分析"),
     ("独立负责 C 语言模块开发", "独立负责一个 C 模块从设计到交付，提交工程、测试与线上证据"),
     ("指针", "内存管理", "编译")),
    (("skill_vlm", "vlm", "vision-language-model", "视觉语言模型"), ("视觉语言模型", "VLM"),
     ("视觉语言模型基础与多模态理解", "完成图文输入、Token 化与多模态推理练习，"
      "提交可运行示例与说明"),
     ("视觉语言模型微调与评测", "完成一次视觉语言模型微调与图文评测，提交数据、训练脚本与指标对比"),
     ("视觉语言模型应用实践", "完成一个面向业务的视觉语言应用，提交数据管线、服务与效果评估"),
     ("独立负责视觉语言模型工程", "独立负责视觉语言模型能力从数据到交付，提交工程、评测与线上验证"),
     ("多模态", "图文理解", "微调评测")),
)

_LEARNING_ASSETS = (
    *_LEARNING_ASSETS,
    *tuple(
        asset
        for spec in _EXTENDED_SKILLS_2
        for asset in _stage_assets(*spec)
    ),
)


def _normalize(value: str | None) -> str:
    return unicodedata.normalize("NFKC", value or "").strip().casefold()


def _build_index() -> tuple[
    dict[str, tuple[LearningAsset, ...]],
    dict[str, tuple[LearningAsset, ...]],
]:
    by_skill: dict[str, list[LearningAsset]] = {}
    by_name: dict[str, list[LearningAsset]] = {}
    for asset in _LEARNING_ASSETS:
        for alias in asset.skill_ids:
            by_skill.setdefault(_normalize(alias), []).append(asset)
        for alias in asset.names:
            by_name.setdefault(_normalize(alias), []).append(asset)
    return (
        {key: tuple(items) for key, items in by_skill.items()},
        {key: tuple(items) for key, items in by_name.items()},
    )


_SKILL_INDEX, _NAME_INDEX = _build_index()


def _stage_matches(asset: LearningAsset, stage: str, target_level: str | None) -> bool:
    if asset.stage != stage:
        return False
    if asset.target_levels and target_level is not None:
        normalized_level = _normalize(target_level)
        if normalized_level not in {_normalize(item) for item in asset.target_levels}:
            return False
    return True


def lookup_learning_asset(
    *,
    skill_id: str | None,
    canonical_name: str | None = None,
    stage: str | None,
    target_level: str | None = None,
) -> LearningAsset | None:
    """Return the deterministic learning asset for a planned action, if any.

    Matching first tries the raw ``skill_id`` aliases, then the canonical skill
    name aliases.  A configured asset must also match the action stage; a
    configured ``target_levels`` restriction is only enforced when the action
    actually carries a target level.  Misses return ``None`` so the existing
    planner templates remain the fallback.
    """
    if stage is None:
        return None
    candidates = _SKILL_INDEX.get(_normalize(skill_id), ()) if skill_id else ()
    if not candidates and canonical_name:
        candidates = _NAME_INDEX.get(_normalize(canonical_name), ())
    for asset in candidates:
        if _stage_matches(asset, stage, target_level):
            return asset
    return None
