from app.domain.json_types import FrozenJsonObject
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol


class SystemStatusPort(Protocol):
    def readiness(self) -> tuple[bool, FrozenJsonObject]: ...
    def database(self) -> FrozenJsonObject: ...
    def vector_store(self) -> FrozenJsonObject: ...
    def model_services(self) -> FrozenJsonObject: ...
    def overall(self) -> FrozenJsonObject: ...


@dataclass(frozen=True)
class SystemConfigRecord:
    name: str
    config: FrozenJsonObject
    version: int
    updated_by: str | None
    updated_at: datetime | None


class SystemConfigRepository(Protocol):
    def get(self, name: str) -> SystemConfigRecord | None: ...
    def add_default(self, name: str, config: FrozenJsonObject) -> SystemConfigRecord: ...
    def update(self, name: str, config: FrozenJsonObject, updated_by: str) -> SystemConfigRecord: ...


class SystemConfigUnitOfWork(Protocol):
    configs: SystemConfigRepository
    def __enter__(self) -> "SystemConfigUnitOfWork": ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
