"""stable_schema_baseline

Revision ID: baseline_0006
Revises: 
Create Date: 2026-07-13 18:33:51.382253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'baseline_0006'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_configs',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('duplicate_clusters',
    sa.Column('cluster_key', sa.String(length=80), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_documents',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('enterprise_name', sa.String(length=160), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_credibility', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_documents_document_id'), 'jd_documents', ['document_id'], unique=True)
    op.create_table('position_categories',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skill_categories',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('category_code', sa.String(length=80), nullable=False),
    sa.Column('subcategory_code', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_category_code'), 'skills', ['category_code'], unique=False)
    op.create_table('standard_positions',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_index(op.f('ix_standard_positions_category_code'), 'standard_positions', ['category_code'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_candidate_requirements',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'requirement_id')
    )
    op.create_table('extracted_job_titles',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('extracted_company_facts',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'fact_id')
    )
    op.create_table('extracted_employment_facts',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'fact_id')
    )
    op.create_table('extracted_task_requirements',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'requirement_id')
    )
    op.create_table('extraction_evidence',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_ref', sa.String(length=80), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.String(length=30), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'owner_type', 'owner_ref')
    )
    op.create_index(op.f('ix_extraction_evidence_document_id'), 'extraction_evidence', ['document_id'], unique=False)
    op.create_table('graph_build_runs',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('base_version_id', sa.Integer(), nullable=True),
    sa.Column('active_draft_key', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_build_runs_base_version_id', 'graph_build_runs', ['base_version_id'], unique=False)
    op.create_index('uq_graph_build_run_active_draft_key', 'graph_build_runs', ['active_draft_key'], unique=True)
    op.create_index('uq_graph_build_run_id_position', 'graph_build_runs', ['id', 'position_id'], unique=True)
    op.create_table('jd_extraction_records',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_extraction_records_document_id'), 'jd_extraction_records', ['document_id'], unique=False)
    op.create_table('jd_normalized_records',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('map_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_normalized_records_document_id'), 'jd_normalized_records', ['document_id'], unique=False)
    op.create_table('jd_quality_assessments',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('duplicate_score', sa.Float(), nullable=False),
    sa.Column('copy_risk_score', sa.Float(), nullable=False),
    sa.Column('inflation_score', sa.Float(), nullable=False),
    sa.Column('effective_sample_weight', sa.Float(), nullable=False),
    sa.Column('assessed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('skill_aliases',
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('unresolved_normalization_items',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_build_samples',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reasons', sa.JSON(), nullable=False),
    sa.Column('effective_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_versions',
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=80), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('normalization_map_version', sa.String(length=50), nullable=False),
    sa.Column('rollback_from_version_id', sa.Integer(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rollback_from_version_id'], ['graph_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'version_name'),
    sa.UniqueConstraint('position_id', 'version_number')
    )
    op.create_index('uq_graph_version_build_run', 'graph_versions', ['build_run_id'], unique=True)
    op.create_table('normalized_job_classifications',
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=True),
    sa.Column('source_title', sa.String(length=200), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['jd_normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_requirement_records',
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['jd_normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_record_id', 'requirement_id')
    )
    op.create_table('position_requirement_aggregate_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_skill_relation_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('auto_weight', sa.Float(), nullable=False),
    sa.Column('manual_weight', sa.Float(), nullable=True),
    sa.Column('final_weight', sa.Float(), nullable=False),
    sa.Column('auto_confidence', sa.Float(), nullable=False),
    sa.Column('manual_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('auto_importance_level', sa.String(length=20), nullable=False),
    sa.Column('manual_importance_level', sa.String(length=20), nullable=True),
    sa.Column('final_importance_level', sa.String(length=20), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id', 'position_id'], ['graph_build_runs.id', 'graph_build_runs.position_id'], name='fk_relation_draft_build_position'),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_run_id', 'skill_id')
    )
    op.create_table('position_task_aggregate_drafts',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('build_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_skill_records',
    sa.Column('normalized_requirement_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=True),
    sa.Column('canonical_name', sa.String(length=200), nullable=True),
    sa.Column('category_code', sa.String(length=80), nullable=True),
    sa.Column('subcategory_code', sa.String(length=80), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('resolution_source', sa.String(length=30), server_default='unresolved', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_requirement_id'], ['normalized_requirement_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_skill_records_category_code'), 'normalized_skill_records', ['category_code'], unique=False)
    op.create_table('review_task_events',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_skill_supports',
    sa.Column('build_run_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('normalized_skill_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('source_requirement_id', sa.Integer(), nullable=False),
    sa.Column('extraction_record_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['graph_build_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['jd_documents.document_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['extraction_evidence.id'], ),
    sa.ForeignKeyConstraint(['extraction_record_id'], ['jd_extraction_records.id'], ),
    sa.ForeignKeyConstraint(['normalized_skill_id'], ['normalized_skill_records.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.position_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['source_requirement_id'], ['extracted_candidate_requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_run_id', 'normalized_skill_id', 'evidence_id')
    )
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute("""CREATE TRIGGER trg_graph_versions_reject_update
        BEFORE UPDATE ON graph_versions BEGIN
        SELECT RAISE(ABORT, 'graph_versions are immutable'); END""")
        op.execute("""CREATE TRIGGER trg_graph_versions_reject_delete
        BEFORE DELETE ON graph_versions BEGIN
        SELECT RAISE(ABORT, 'graph_versions are immutable'); END""")
        op.execute("""CREATE TRIGGER trg_extraction_payload_reject_update
        BEFORE UPDATE OF payload ON jd_extraction_records
        WHEN NEW.payload IS NOT OLD.payload BEGIN
        SELECT RAISE(ABORT, 'extraction audit payload is immutable'); END""")
    elif dialect == "postgresql":
        op.execute("""CREATE FUNCTION reject_graph_version_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'graph_versions are immutable'
        USING ERRCODE = 'integrity_constraint_violation'; END; $$""")
        op.execute("""CREATE TRIGGER trg_graph_versions_reject_update BEFORE UPDATE
        ON graph_versions FOR EACH ROW EXECUTE FUNCTION reject_graph_version_mutation()""")
        op.execute("""CREATE TRIGGER trg_graph_versions_reject_delete BEFORE DELETE
        ON graph_versions FOR EACH ROW EXECUTE FUNCTION reject_graph_version_mutation()""")
        op.execute("""CREATE FUNCTION reject_extraction_payload_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
        IF NEW.payload IS DISTINCT FROM OLD.payload THEN
        RAISE EXCEPTION 'extraction audit payload is immutable'
        USING ERRCODE = 'integrity_constraint_violation'; END IF;
        RETURN NEW; END; $$""")
        op.execute("""CREATE TRIGGER trg_extraction_payload_reject_update
        BEFORE UPDATE ON jd_extraction_records FOR EACH ROW
        EXECUTE FUNCTION reject_extraction_payload_mutation()""")
    else:
        raise RuntimeError(f"baseline does not support dialect {dialect!r}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_graph_versions_reject_update ON graph_versions")
        op.execute("DROP TRIGGER IF EXISTS trg_graph_versions_reject_delete ON graph_versions")
        op.execute("DROP TRIGGER IF EXISTS trg_extraction_payload_reject_update ON jd_extraction_records")
        op.execute("DROP FUNCTION IF EXISTS reject_graph_version_mutation()")
        op.execute("DROP FUNCTION IF EXISTS reject_extraction_payload_mutation()")
    else:
        op.execute("DROP TRIGGER IF EXISTS trg_graph_versions_reject_update")
        op.execute("DROP TRIGGER IF EXISTS trg_graph_versions_reject_delete")
        op.execute("DROP TRIGGER IF EXISTS trg_extraction_payload_reject_update")
    op.drop_table('position_skill_supports')
    op.drop_table('review_task_events')
    op.drop_index(op.f('ix_normalized_skill_records_category_code'), table_name='normalized_skill_records')
    op.drop_table('normalized_skill_records')
    op.drop_table('review_tasks')
    op.drop_table('position_task_aggregate_drafts')
    op.drop_table('position_skill_relation_drafts')
    op.drop_table('position_requirement_aggregate_drafts')
    op.drop_table('normalized_requirement_records')
    op.drop_table('normalized_job_classifications')
    op.drop_index('uq_graph_version_build_run', table_name='graph_versions')
    op.drop_table('graph_versions')
    op.drop_table('graph_build_samples')
    op.drop_table('unresolved_normalization_items')
    op.drop_table('skill_aliases')
    op.drop_table('jd_quality_assessments')
    op.drop_index(op.f('ix_jd_normalized_records_document_id'), table_name='jd_normalized_records')
    op.drop_table('jd_normalized_records')
    op.drop_index(op.f('ix_jd_extraction_records_document_id'), table_name='jd_extraction_records')
    op.drop_table('jd_extraction_records')
    op.drop_index('uq_graph_build_run_id_position', table_name='graph_build_runs')
    op.drop_index('uq_graph_build_run_active_draft_key', table_name='graph_build_runs')
    op.drop_index('ix_graph_build_runs_base_version_id', table_name='graph_build_runs')
    op.drop_table('graph_build_runs')
    op.drop_index(op.f('ix_extraction_evidence_document_id'), table_name='extraction_evidence')
    op.drop_table('extraction_evidence')
    op.drop_table('extracted_task_requirements')
    op.drop_table('extracted_employment_facts')
    op.drop_table('extracted_company_facts')
    op.drop_table('extracted_candidate_requirements')
    op.drop_table('extracted_job_titles')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_standard_positions_category_code'), table_name='standard_positions')
    op.drop_table('standard_positions')
    op.drop_index(op.f('ix_skills_category_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('skill_categories')
    op.drop_table('position_categories')
    op.drop_index(op.f('ix_jd_documents_document_id'), table_name='jd_documents')
    op.drop_table('jd_documents')
    op.drop_table('duplicate_clusters')
    op.drop_table('algorithm_configs')
    # ### end Alembic commands ###


