"""initial_schema

Revision ID: f3819d64bc82
Revises:
Create Date: 2026-07-11 22:59:05.533481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3819d64bc82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("dataset_type in ('jd', 'resume', 'match')", name='ck_evaluation_datasets_type_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_dataset_type'), ['dataset_type'], unique=False)

    op.create_table('evidence_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('related_object_type', sa.String(length=64), nullable=True),
    sa.Column('related_object_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_sources_related_object_id'), ['related_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_sources_related_object_type'), ['related_object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_sources_source_type'), ['source_type'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('enterprise_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('copy_risk_score', sa.Float(), nullable=True),
    sa.Column('inflation_score', sa.Float(), nullable=True),
    sa.Column('is_downweighted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("parse_status in ('pending', 'running', 'completed', 'failed')", name='ck_job_descriptions_parse_status_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('position_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('time_window_start', sa.Date(), nullable=True),
    sa.Column('time_window_end', sa.Date(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('core_skills', sa.JSON(), nullable=False),
    sa.Column('representative_titles', sa.JSON(), nullable=False),
    sa.Column('representative_jd_ids', sa.JSON(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('distance_from_existing_positions', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active', 'archived')", name='ck_position_clusters_status_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('prediction_basis', sa.JSON(), nullable=False),
    sa.Column('related_source_ids', sa.JSON(), nullable=False),
    sa.Column('potential_responsibilities', sa.JSON(), nullable=False),
    sa.Column('potential_skills', sa.JSON(), nullable=False),
    sa.Column('industry_scenarios', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('candidate', 'verified', 'published', 'rejected')", name='ck_predicted_positions_status_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('modified_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority in ('low', 'normal', 'high', 'urgent')", name='ck_review_tasks_priority_allowed'),
    sa.CheckConstraint("status in ('pending', 'claimed', 'approved', 'rejected', 'modified')", name='ck_review_tasks_status_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_skill_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_skill_name'), ['skill_name'], unique=True)

    op.create_table('standard_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('source_emerging_position_id', sa.String(length=36), nullable=True),
    sa.Column('core_responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('bonus_skills', sa.JSON(), nullable=False),
    sa.Column('industry_scenarios', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_positions_source_emerging_position_id'), ['source_emerging_position_id'], unique=False)

    op.create_table('trend_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('parsed_keywords', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type in ('policy', 'report', 'paper', 'webpage')", name='ck_trend_sources_type_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_sources_source_type'), ['source_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('personal_user', 'enterprise_user', 'admin', 'reviewer', 'developer')", name='ck_users_role_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('emerging_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('core_responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('bonus_skills', sa.JSON(), nullable=False),
    sa.Column('industry_scenarios', sa.JSON(), nullable=False),
    sa.Column('germination_score', sa.Float(), nullable=True),
    sa.Column('score_dimensions', sa.JSON(), nullable=False),
    sa.Column('evidence_jd_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('candidate', 'verified', 'published', 'rejected')", name='ck_emerging_positions_status_allowed'),
    sa.ForeignKeyConstraint(['cluster_id'], ['position_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emerging_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emerging_positions_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('enterprises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('scale', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active', 'inactive')", name='ck_enterprises_status_allowed'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprises_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('evaluation_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('error_cases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("report_type in ('jd_parse', 'resume_parse', 'match', 'skill_normalization', 'cluster')", name='ck_evaluation_reports_type_allowed'),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_reports_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_reports_report_type'), ['report_type'], unique=False)

    op.create_table('jd_parse_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jd_id', sa.String(length=36), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('bonus_skills', sa.JSON(), nullable=False),
    sa.Column('education', sa.String(length=64), nullable=True),
    sa.Column('experience', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('business_scenarios', sa.JSON(), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('need_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jd_parse_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jd_parse_results_jd_id'), ['jd_id'], unique=True)

    op.create_table('match_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('use_enterprise_weights', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('radar', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('weak_skills', sa.JSON(), nullable=False),
    sa.Column('bonus_skills', sa.JSON(), nullable=False),
    sa.Column('project_match', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_reports_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_reports_user_id'), ['user_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("parse_status in ('pending', 'running', 'completed', 'failed')", name='ck_resumes_parse_status_allowed'),
    sa.CheckConstraint("source_type in ('text', 'file', 'image')", name='ck_resumes_source_type_allowed'),
    sa.ForeignKeyConstraint(['file_id'], ['file_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('review_task_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before_status', sa.String(length=32), nullable=True),
    sa.Column('after_status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_task_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_task_events_task_id'), ['task_id'], unique=False)

    op.create_table('skill_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'alias', name='uq_skill_aliases_skill_alias')
    )
    with op.batch_alter_table('skill_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_aliases_skill_id'), ['skill_id'], unique=False)

    op.create_table('skill_normalization_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_skill', sa.String(length=128), nullable=False),
    sa.Column('candidate_skill_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('pending', 'confirmed', 'rejected')", name='ck_skill_normalization_candidates_status_allowed'),
    sa.ForeignKeyConstraint(['candidate_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_normalization_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_normalization_candidates_raw_skill'), ['raw_skill'], unique=False)

    op.create_table('trend_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('time_window_start', sa.Date(), nullable=True),
    sa.Column('time_window_end', sa.Date(), nullable=True),
    sa.Column('current_graph', sa.JSON(), nullable=False),
    sa.Column('skill_weight_distribution', sa.JSON(), nullable=False),
    sa.Column('new_skills', sa.JSON(), nullable=False),
    sa.Column('rising_skills', sa.JSON(), nullable=False),
    sa.Column('declining_skills', sa.JSON(), nullable=False),
    sa.Column('replaced_skills', sa.JSON(), nullable=False),
    sa.Column('skill_combo_shifts', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'published')", name='ck_trend_reports_status_allowed'),
    sa.ForeignKeyConstraint(['position_id'], ['standard_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_reports_position_id'), ['position_id'], unique=False)

    op.create_table('enterprise_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('standard_position_id', sa.String(length=64), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'published', 'paused', 'cancelled')", name='ck_enterprise_jobs_status_allowed'),
    sa.CheckConstraint('headcount >= 0', name='ck_enterprise_jobs_headcount_nonnegative'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_jobs_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_report_id', sa.String(length=36), nullable=False),
    sa.Column('target_position_id', sa.String(length=36), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_report_id'], ['match_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_match_report_id'), ['match_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_paths_target_position_id'), ['target_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_paths_user_id'), ['user_id'], unique=False)

    op.create_table('resume_parse_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('internships', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('certificates', sa.JSON(), nullable=False),
    sa.Column('competitions', sa.JSON(), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('need_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_parse_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_parse_results_resume_id'), ['resume_id'], unique=True)

    op.create_table('resume_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('raw_skill', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.String(length=255), nullable=True),
    sa.Column('proficiency', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_skills_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('enterprise_job_skill_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_job_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weight >= 0', name='ck_enterprise_job_weights_nonnegative'),
    sa.ForeignKeyConstraint(['enterprise_job_id'], ['enterprise_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_job_skill_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_job_skill_weights_enterprise_job_id'), ['enterprise_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_job_skill_weights_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_job_skill_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_job_skill_weights_skill_id'))
        batch_op.drop_index(batch_op.f('ix_enterprise_job_skill_weights_enterprise_job_id'))

    op.drop_table('enterprise_job_skill_weights')
    with op.batch_alter_table('resume_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_resume_skills_resume_id'))

    op.drop_table('resume_skills')
    with op.batch_alter_table('resume_parse_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_parse_results_resume_id'))

    op.drop_table('resume_parse_results')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_paths_target_position_id'))
        batch_op.drop_index(batch_op.f('ix_learning_paths_match_report_id'))

    op.drop_table('learning_paths')
    with op.batch_alter_table('enterprise_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_jobs_enterprise_id'))

    op.drop_table('enterprise_jobs')
    with op.batch_alter_table('trend_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_reports_position_id'))

    op.drop_table('trend_reports')
    with op.batch_alter_table('skill_normalization_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_normalization_candidates_raw_skill'))

    op.drop_table('skill_normalization_candidates')
    with op.batch_alter_table('skill_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_aliases_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_aliases_alias'))

    op.drop_table('skill_aliases')
    with op.batch_alter_table('review_task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_task_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_review_task_events_actor_user_id'))

    op.drop_table('review_task_events')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('match_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_match_reports_resume_id'))

    op.drop_table('match_reports')
    with op.batch_alter_table('jd_parse_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jd_parse_results_jd_id'))

    op.drop_table('jd_parse_results')
    with op.batch_alter_table('evaluation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_reports_dataset_id'))

    op.drop_table('evaluation_reports')
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprises_owner_user_id'))

    op.drop_table('enterprises')
    with op.batch_alter_table('emerging_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emerging_positions_cluster_id'))

    op.drop_table('emerging_positions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trend_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_sources_source_type'))

    op.drop_table('trend_sources')
    with op.batch_alter_table('standard_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_positions_source_emerging_position_id'))

    op.drop_table('standard_positions')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_skill_name'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_object_type'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_object_id'))

    op.drop_table('review_tasks')
    op.drop_table('predicted_positions')
    op.drop_table('position_clusters')
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_enterprise_id'))

    op.drop_table('job_descriptions')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_owner_user_id'))

    op.drop_table('file_assets')
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_sources_related_object_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_sources_related_object_id'))

    op.drop_table('evidence_sources')
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_dataset_type'))

    op.drop_table('evaluation_datasets')
    # ### end Alembic commands ###
