from __future__ import annotations

from datetime import datetime
from typing import Protocol


class CredibilityStore(Protocol):
    def active_versions(self) -> dict[str, str]: ...
    def payloads(self, versions: dict[str, str]) -> dict[str, dict]: ...
    def create_configuration(self, value: dict[str, object]) -> dict[str, object]: ...
    def list_configurations(self, config_type: str | None = None) -> list[dict[str, object]]: ...
    def get_configuration(self, config_id: str) -> dict[str, object] | None: ...
    def transition(self, config_id: str, action: str, actor: str, note: str | None = None) -> dict[str, object] | None: ...
    def history(self, config_id: str) -> list[dict[str, object]] | None: ...
    def compare(self, left_id: str, right_id: str) -> dict[str, object] | None: ...
    def eligible_snapshot_terms(self, cutoff: datetime) -> list[dict[str, object]]: ...
    def create_backtest(self, request: dict[str, object], versions: dict[str, str]) -> tuple[dict[str, object], bool]: ...
    def save_backtest_results(self, run_id: str, slices: list[dict[str, object]]) -> None: ...
    def get_backtest(self, run_id: str) -> dict[str, object] | None: ...
    def backtest_results(self, run_id: str) -> list[dict[str, object]] | None: ...
