"""Stable default values shared by configuration use cases and adapters."""

DEFAULT_CONFIGS: dict[str, dict] = {
    "algorithms": {"mode": "emerge_v3_2", "version": "emerge-v3.2"},
    "llm": {
        "enabled": False,
        "provider": "deepseek",
        "base_url": "https://api.deepseek.com",
        "model": "deepseek-v4-flash",
    },
    "embedding": {"enabled": False, "provider": "deterministic_local", "dimension": 16},
    "clustering": {
        "algorithm": "occupation_title_key",
        "version": "occupation-title-key-v1",
        "stage2_unit": "occupation_cluster",
    },
    "match-weights": {"skill": 0.6, "project": 0.2, "scenario": 0.2},
    "germination-score": {
        "growth": 0.22,
        "novelty": 0.22,
        "diversity": 0.16,
        "industry_spread": 0.14,
        "distance": 0.26,
        "minimum_sample_size": 3,
        "minimum_source_count": 2,
        "target_source_count": 3,
        "target_industry_count": 3,
        "sample_size_penalty": 0.15,
        "single_platform_noise_penalty": 0.08,
        "duplicate_sample_penalty": 0.20,
        "emerging_threshold": 0.60,
        "high_potential_threshold": 0.75,
        "minimum_stability_score": 0.65,
        "formula_version": "emergence-index-v4-seven-dimensions",
        "formal_algorithm_version": "emerge-v3.2",
        "candidate_clustering_version": "occupation-title-key-v1",
        "stage2_unit": "occupation_cluster",
        "semantic_failure_mode": "fail",
        "candidate_identity_linker_version": "identity-v2-semantic-temporal-verifier.v1",
        "candidate_lifecycle_version": "candidate-lifecycle-v2",
        "split_refinement_enabled": False,
        "anti_over_split_guards": True,
        "company_partition_requires_contradiction": True,
        "lineage_admission_version": "v2",
    },
    "trend-analysis": {"new_skill": 0.3, "rising_skill": 0.3, "risk": 0.4},
}
